### ISSUE TITLE
Review the use of ctid in the json schema

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/CredentialRegistry#1]
per @leolara
I see there are 41 classes that have ctid property, and that they are referenced from other schemas using meta:identifier. I guess these are what I called the entities. And the rest that are not either literals nor entities, are the sub-entities.

MP - @siuc-nate I thought the use of CTID had been greatly scaled back?

**Comment by stuartasutton** [comment]
Michael, where are you seeing 41 classes that have the `ctid` property? 

That is incorrect. The only classes with `ctid` property are `Credential` and its subclasses. See http://www.credreg.net/ctdl/terms#ctid.

**Comment by leolara** [comment]
@stuartasutton shouldn't issuers of credentials also have their own id?

**Comment by leolara** [comment]
@stuartasutton @mparsons1953 I look into it more and I see 22 classes that have ctid, I used a search in the json and I wasn't carful enough to count duplicates.

I do not know if 22 are too many, it is a design decision.

My point now would be, aren't the organisations that issue credentials going to have their own id so they can be referenced?

**Comment by leolara** [comment]
I see acreditedBy filed type is meta:identifier, but how is the ID called in the target entity?

**Comment by leolara** [comment]
I see accreditedBy points to http://www.credreg.net/ctdl/terms#QACredentialOrganization but it seems to do not have a primary key.

**Comment by stuartasutton** [comment]
@leolara, what I meant is that the only types (classes) in the model with a `ctid` property are `Credential` and its (22) subclasses. I'm not able to address the matter of "primary key" for instances of any of the other types since the core model is RDF meaning that instances of entities are identified by URI--i.e., with `@id` in jsonld. 

But, I have to apologize because my knowledge of json schema is massively limited and I may be totally misunderstanding the issue.

**Comment by siuc-nate** [comment]
22 classes is correct. 

As for assigning ctid to Organizations or other entities, we went back and forth on this a few times. I believe (correct me if I'm wrong, @stuartasutton ) that we determined that JSON-LD's "@id" property would be sufficient.

**Comment by leolara** [comment]
@siuc-nate @stuartasutton 

It might be that we should put the CTID on the @id as well?

One important point is if those reffered entities that do not have CTID are going to be stored in the registry?

ctid urn is a URI, am I right?

**Comment by siuc-nate** [comment]
Assuming the registry enables a URI along the lines of:
http://credentialregistry.org/resource/{identifier}
where {identifier} is either a ctid or just a UUID (for credentials and for everything else, respectively), then I _believe_ the JSON-LD could probably use either a CTID or a url + CTID (as above) for the `@id` properties.  However, I am not 100% sure.

**Comment by stuartasutton** [comment]
While a urn is a kind of uri, I'd not put `ctid` on a list for @id in the JSON-LD. Functionally, `ctid` is no different than a raft of other CTDL identifiers (e.g.., `fein`, `duns`, `opeID` etc.). It's special status within CTDL is as a kind of product ID for a credential, but not as the basis for identifying an instance of Credential code--i.e., no substitute for a full http-based uri.

We did decide that the `ctid` could be used to construct an http-based URI for the RDF identifier for instances of `Credential`. I.e., <http://credreg.net/resources/[ctid]>

So, we might see something like this in instance data:

```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@id": "http://credreg.net/resources/urn:ctid:fb6ef053-fae7-4818-9182-e13f718c3431",
  "@type": "ceterms:Credential",
  "ceterms:ctid": "urn:ctid:fb6ef053-fae7-4818-9182-e13f718c3431"
}
```
Perhaps `_:urn:ctid:fb6ef053-fae7-4818-9182-e13f718c3431` if identifying a `Credential` as bNode...but when would we ever do that?

But again, I am on the slippery edge of what I know of JSON and clearly on the edge of what you guys are doing.

**Comment by leolara** [comment]
@science @stuartasutton I am not sure I understand completely, wasn't the idea of using a opaque ID also to try to make the protocol and the data open. Doesn't making the IDs linked to a domain name defy that?

regarding the bnode I just read a bit about it in the JSON-LD as I do not have a deep understanding, but I think your point is correct that we will not use a credential as bnode, because the registry will force it to have a @id field on upload

**Comment by science** [comment]
@leolara @stuartasutton - Leo, I believe that the CTI team made a decision recently that they would host the identifiers at URLs, as a resolver service for the URNs. So the URL ID would be this:
`http://credreg.net/resources/urn:ctid:fb6ef053-fae7-4818-9182-e13f718c3431`

The URN would obviously be this:
`urn:ctid:fb6ef053-fae7-4818-9182-e13f718c3431`

And the relationship between the two would be described in the URN application. However, if in the future, the community determined that the URN resolution would be handled by a different URL, an amendment to the URN application could be made, informing everyone of the new resolver service.

I believe this keeps things simple and manageable for CTI right now, without precluding the possibility of changes to resolution services in the future (via the URN registration). Also since all the CTDL credentials including their URNs are backed up to archive.org, it's possible for someone to stand up a new resolver service long after this project is sleeping for whatever reason.

@stuartasutton's main point I think is that in order for the RDF / linked data on the web to work well, we want HTTP / URL resolutions for everything. But we also want URNs in the mix, to allow us to swap out our resolver, in the future (obviously there would be significant difficulties in doings so, but the URN enables the concept for sure).

Anyone who doesn't trust the URL, can internally store just the URN and function just fine. Seem ok?

**Comment by leolara** [comment]
@science @stuartasutton my point is specifically about the ```@id``` field. This should be immutable as it is my understanding. Hence, I think in ```@id``` we should have the urn, that is a valid URI. We can have the URL ID in some other field, as this is almost but not 100% immutable.

Is that right?

**Comment by science** [comment]
This is definitely a question for @stuartasutton and @siuc-nate! I believe that the current plan is to use the credreg URLs for @id's but as you say they are not 100% immutable. I hope they can weigh in to let us know on this point.

**Comment by stuartasutton** [comment]
I feel a bit like I am dropping into the middle of a conversation. I'm confused about how the URI identifying a resource (here a credential) is any more immutable than the ctid. So, using Steve's example, the following are equally immutable given the social contract by CE behind the (http) URI identifying resources in the CER:

> http://credreg.net/resources/urn:ctid:fb6ef053-fae7-4818-9182-e13f718c3431
urn:ctid:fb6ef053-fae7-4818-9182-e13f718c3431

While a URN is a form of URI, it does not inherently specify a way to retrieve the thing it identifies as does the HTTP-based URI.

I don't think we'd be having this conversation if the resource were not the credential. Instances of learning opportunity and assessment descriptions (that have no such notion as the CTID) are named/identified by (http) URI e.g.:

> http://credreg.net/resources/83f05f51-618b-44f3-806c-066365254a8b

I don't think credentials call for any different treatment (except for the concatenation of the URN as opposed to simple concatenation of UUID.

**Comment by siuc-nate** [comment]
Is the problem just that the URL part ("http://credentialregistry.org/resource/") part might change? If so, could we use a PURL or something?  e.g.
http://purl.org/credentialregistry/resource/urn:ctid:[UUID]

Then the purl could redirect to whatever host system.  I would want to have the /resource/ part in the middle for flexibility/future-proofing in case we want to setup other services (which I assume we eventually will) under the same PURL structure. 

Anyway, it does make sense to me that the `@id` property should always be a resolvable full URI.

**Comment by stuartasutton** [comment]
We've discussed several (many?) times the pros and cons of using PURLS for resource URI other than the CTDL schema. The conclusion (I thought) was that we'd not use PURLS and rely instead on a clear namespace policy and organizational understandings around the transfer of the namespace should Credential Engine ever cease and the metadata asserts be transferred.

**Comment by science** [comment]
I agree that we've been up and down this hill. Sorry Stuart and Nate - I just wanted you to weight b/c Leo was asking. I think Leo is pointing out that a URL is not immutable b/c it's possible to lose control of the URL domain. We all agree that this is an acceptable risk to the project. 

So for purposes of @id fields in the json-ld structures, we will use URLs (w/credreg domain) as immutable URIs that contain the URNs for the credentials. 

Hopefully that's enough to move forward @leolara? Thanks for being triple sure this is the path we're on.

**Comment by leolara** [comment]
Closing this issue then

**Comment by siuc-nate** [comment]
One last thing then - are we using http://credentialregistry.org/resource/{identifier} or http://credreg.net/resource/{identifier} ?  Considering credreg.net is the site for the schema itself, I don't know if we'd want to confuse that with also being the site for instances of credentials.

Oh, and while we're at it, since it will come up one day, should we use http:// or https:// ?

**Comment by science** [comment]
Seems to me that it should be http: - these are public resources on the public web. I'd vote for credentialregistry.org (what happened to credential engine registry, though that's a bit off topic?).

**Comment by stuartasutton** [comment]
@siuc-nate, I'm game for either http://credreg.net or http://credentialregistry.org. BUT, you'd better check through the github issues (or maybe @mparsons1953 remembers) and make sure what the precise decision was with our discussion with Jeanne. Let's try not to open up discussions again.

**Comment by leolara** [comment]
@science @stuartasutton 

Please consider as well that there can be changes in technology, like it could be one day browsers stop supporting ```http``` as they considers it insecure, or that in 10 years perhaps everyone is using superhttps:// urls

**Comment by siuc-nate** [comment]
@stuartasutton I believe this is the thread:
https://github.com/CredentialEngine/vocabularies/issues/176

**Comment by jkitchensSIUC** [comment]
SIUC can/will purchase the CE domain for the registry.

**Comment by leolara** [comment]
I close this issue then
