### ISSUE TITLE
Decide if we are going to use JSON Schema as documentation for the developers

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#10]

**Comment by science** [comment]
I would like to! It implies that the JSON schema is easy to read and "self-documenting."

If that's not possible then probably it's just usable for validation. I'm guessing others are worried about using it in this way?

**Comment by leolara** [comment]
@science it is possible. You can add fields like title, description or even example to the JSON schema sub-schemas for each field, so it becomes self documenting.

I believe we could even create pretty documentation and a data model editor from the JSON schema automatically

**Comment by leolara** [comment]
Here we have the description of the top level classes added:

http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true&includeDescriptions=true

If we want to use this as documentation, we should add the description to all fields, etc...

**Comment by science** [comment]
I believe @andersoncardoso already set up some links to Swagger inside the JSON schema files we were generating? Or something like that..

**Comment by leolara** [comment]
@science @andersoncardoso  I am not sure. Swagger is for the API, that is kind of agnostic of the JSON Schema, if I understand correctly

I think the best way to explain developers how to create the credentials is to provide the json schema, from the pure CTDL there are infinite ways of expressing it on JSON-LD, but only one that conforms with our schema

**Comment by science** [comment]
+1 to narrowing the range of expression of the CTDL to one structure per entity. The big question is whether we can autogenerate those structures in a way that makes them intuitive and readable? Some JSON-LD is really hard to read.

I was wrong about the Swagger links (I went and looked).

One related issue when we are generating these validations: In some cases we will probably want some custom validations that are not provided by the spec natively. We need some way to name those custom validations on @siuc-nate's side, and then write the custom validation handlers on our side that are activated when they see a custom validation specified. Probably not a pressing issue, but will matter to devs, as they will want to know how the custom validation is specified.

**Comment by leolara** [comment]
@science I have the impression that it is out the topic of this issue about using the JSON Schema as the documentation.

We have other issue to cover these:

https://github.com/CredentialEngine/CredentialRegistry/issues/8

https://github.com/CredentialEngine/CredentialRegistry/issues/11

**Comment by andersoncardoso** [comment]
@science @leolara 
We have at least one case of custom validation. On the `ctid`, we check for uniqueness.

**Comment by leolara** [comment]
@andersoncardoso so we use the extensible JSON schema field `format` or is it hardcoded?

The right way to do it would be to have in the JSON Schema `"format": "ctid"`  and then add a custom validator for it.

Another thing, isn't this a bit off topic?

this issue is a bit about whether we are going to hide the JSON Schema from the developers

**Comment by andersoncardoso** [comment]
taken from the docs: `format support is optional, and as such other tools may ignore this keyword: this can lead to a different validation outcome for the same data;`
Regardless of the way we signal to the schema validator which method to use, the code has to be on the model, since this is a DB check, we can't know if the ctid is unique only with the json data. For now we check using the attribute key, but we can use the 'format' without problem :+1:

sorry for the off-topic, I was just answering Steve's message about the custom validators.

**Comment by siuc-nate** [comment]
Not to take the thread further off-topic, but to update a credential's data, don't you need to use the same CTID as the original so the system knows which credential to update? Or is there a clear/separate update process that you would use for this (vs publishing a new credential)?

**Comment by leolara** [comment]
@siuc-nate I think it should use `@id` so it works for all the classes

what are we using @andersoncardoso ?

I think it we interpret format="ctid" to mean that we should check it is a uuid and it is the right most part of `@id`  and then, we have for all the objects that @id is unique it is more general

**Comment by andersoncardoso** [comment]
For updating an envelope, the `envelope_id` must be the same, since all resources are  contained inside an envelope (that's a general rule regardless of community or resource) [0].
On the resource level, the property currently checked for uniqueness is the `ctid`. But we can change this.

On a side note: when creating a new envelope, you can provide the envelope_id if you wish, as long as it's unique (the system generates one for you when it's absent). So, maybe, a good approach would be to set the envelope_id to be equal the `ctid` (or @id).

[0] https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/02_ce-registry_walkthrough.md#7---updating-the-resource

**Comment by leolara** [comment]
@andersoncardoso 

 + Not all resources will have `ctid` field, so we should consider `@id` the id as it is unique for the resources
 + I thought an envelope was an update to a resource, and I thought different versions of the same resource that are updated would have different envelopes
 + On update the resources should be matched by their `@id` field. Is not that so? Is the envelop_id used?

**Comment by leolara** [comment]
To the main question here, the answer is yes
