### ISSUE TITLE
Create JSON Schema for the four categories of top-level entities

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#11]

**Comment by andersoncardoso** [comment]
https://github.com/CredentialEngine/CredentialRegistry/tree/master/app/schemas/ce_registry

**Comment by leolara** [comment]
@andersoncardoso Yes, I think they are using that as reference, but the CTDL has changed a lot since then :-)

**Comment by andersoncardoso** [comment]
yes, the schemas has changed, but the organization into 4 categories, each with its own schema and config, it's the same, right?
Or this task is about *updating* the resource (top-level entity) schemas?

**Comment by leolara** [comment]
@andersoncardoso this task is for @siuc-nate to create the new schema

I will create a task for updating the search config from the new schema

**Comment by siuc-nate** [comment]
I have added a parameter you can pass:
?asGroup=true

This will look for things within the same group (which is defined in the data set that the CTDL metadata viewer pulls from; it's _technically_ not part of the schema itself but it has been used in a few other places because it's very handy. You can see the groups at the bottom of the page here: http://credreg.net/ctdl/terms#groups ) and return them as if you had requested the entire set:

http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

Note that AssessmentProfile and LearningOpportunityProfile don't actually have anything in their groups, so what you get back is the same result as if you hadn't passed the parameter at all.

**Comment by leolara** [comment]
@siuc-nate Looking at Credential group json schema, one thing that is important is that either you reference or embedded, you cannot put both even in JSON-LD that can be valid.

Because if something is embedded it will not be a retrievable top level entity.

For example:

```js
    "ceterms:advancedStandingFrom": {
      "anyOf": [
        {
          "$ref": "#/definitions/meta:identifier"
        },
        {
          "$ref": "#/definitions/ceterms:ConditionProfile"
        }
      ]
    },
```

Is class ceterms:ConditionProfile a top level entity, or a sub-entity.

If it is an entity it should be "$ref": "#/definitions/meta:identifier" only, if it is a sub-entity "$ref": "#/definitions/ceterms:ConditionProfile"

Never mix fields that can be identifiers or embedded.

Perhaps this was confused when I suggested using something "$ref": "#/definitions/ceterms:ConditionProfile**ID**" to highlight the type of the referred to the developer.

**Comment by leolara** [comment]
@siuc-nate this last thing I think it is kind of high priority

**Comment by leolara** [comment]
Moved the last issue to #19 and close this one
