### ISSUE TITLE
What's the expected returned when resolving a credential's URI

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CredentialRegistry#125]
What should be the expected behavior when someone puts an existing credential URI (or assessmentProfile, learningOpportunityProfile URI) into a browser. E.g., the Bachelor of Science in Information Technology from the Western Governors University:

http://credentialEngineRegistry.org/resources/ce-CB8EB8D0-208D-4DA0-9F50-7003F8A39ED6

Currently, nothing happens until the browser times out. 

To be more specific, I am talking about resolving the resource URI and not the resource ctid.

**Comment by leolara** [comment]
@stuartasutton I guess what you mean is that we should provide a 404 instead of timeout if the resource does not exist?

The reason why this is happening is that the domain http://credentialengineregistry.org/ is not set up yet. So even if you go to http://credentialengineregistry.org/ you will get a timeout.

**Comment by stuartasutton** [comment]
Thanks, @leolara. Your domain setup comment answers the question. I was using the URI of an resource I knew was in the registry so a 404 would not have been appropriate.
