### ISSUE TITLE
Script that updates schemas in CredReg taking them from https://github.com/CredentialEngine/CTDL_Json_Validation_Schema

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#131]

**Comment by coffeejunk** [comment]
We do have a [script that does this](https://github.com/CredentialEngine/CredentialRegistry/blob/master/bin/update_json_schemas) only the folder needs to be adjusted.

**Comment by leolara** [comment]
@coffeejunk perhaps add the folder as a parameter and that is it?

**Comment by coffeejunk** [comment]
yeah I could do that, I've refrained from spending more time on the script as the past updates have involved other manual changes (schemas were added/renamed) and the date part was the least amount of work :)

**Comment by leolara** [comment]
@coffeejunk changing the date to a parameter seems trivial, and that change will always be needed, right?

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk @jbaird123 
Instead of having to change the date for each new release folder/date, perhaps we could just have a single 'production' folder (or some appropriate name). We could continue to have folders for each bi-monthly release. Whenever we are ready to push an update to 'production', I could just copy the schema files from the working release folder into the production folder. Then the script would be triggered, and always reference the same folder.
