### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#14]
Clean code and files that are unused or obsolete. Perhaps refactor something that is necessary.

Please time box to 4 hours

**Comment by leolara** [comment]
@andersoncardoso coordinate with @coffeejunk so we do not clash on this. but I stil think it is a good idea that @andersoncardoso does this if he has time

**Comment by andersoncardoso** [comment]
This one worth some serious consideration, because if we want to remove the code related to learning-registry, we are bound to a big refactor. 
Given the code was initially made for it, a lot (maybe most) test sample data, and some checks were designed to handle it. 
Removing this, despite possible, will involve a lot of work, and possibly leave things less reliable given that the current code was tested by hand many times, imported several loads of data and etc. We know this works well, changing might introduce new "unknowns". 
If we have time and hands it's ok, anyway it's your call. 

Besides the learning-registry specific code there is nothing really to 'clean'. 
This one is very well crafted from the start (kudos to @aspino , I just maintained his way). 
Has several checks from rubocop and etc via overcommit, has a very high grade on codeclimate, close to 100% coverage and etc.
https://codeclimate.com/github/learningtapestry/learningregistry
https://coveralls.io/github/learningtapestry/learningregistry?branch=master

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by rsaksida** [comment]
I'm not sure about priorities and budget/timeline constraints, but the API project still has a lot of left-over code related to the Learning Registry and a clean-up and refactoring effort would be beneficial.

**Comment by edgarf** [comment]
@neaf can you review how much of this issue is actual?
