### ISSUE TITLE
Need to be able getting an envelope by CTID

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#146]
Currently retrieving a document by CTID returns the JSON-LD, but not the envelope. 
There are a few cases where it would be useful to be able to retrieve the related envelope for a CTID:
- to determine the last update date
- to get a version history from the node_headers

**Comment by jbaird123** [comment]
This should be possible to achieve through a link like this:

http://lr-staging.learningtapestry.com/envelopes/resources/ce-3cee9a46-97a7-41f2-955b-0220c4cead5a

That should return an envelope.  Currently it does not work though.  We'll take care of it.

**Comment by andersoncardoso** [comment]
@jbaird123 @cwd-mparsons 
We have this implemented through search: 
http://lr-staging.learningtapestry.com/ce-registry/search?ctid=ce-3cee9a46-97a7-41f2-955b-0220c4cead5a

**Comment by cwd-mparsons** [comment]
@andersoncardoso @jbaird123 Makes perfect sense, thanks.

**Comment by siuc-nate** [comment]
Now that the registry is more mature, it would make sense to implement this as a proper endpoint rather than requiring a search workaround.

**Comment by excelsior** [comment]
@siuc-nate @mparsons-ce

Can confirm, it hasn't been implemented yet.

Should this API be public, i.e. accessible by unauthenticated users? Also, what would be the preferred endpoint? I can suggest using something like `/resources/documents/{ctid}`, but maybe you guys have something better in mind?

**Comment by mparsons-ce** [comment]
@excelsior 
Yes, this will be a public endpoint. 
I would think that since /**resources**/.. returns a payload, we should not use it in the endpoint for an envelope.
Options:
Per Alex: Adding a path under /envelopes
**/envelopes/documents/{ctid}**

Using a singular **envelope**. This could be confusing but I like the shorter endpoint:
/envelope/{ctid}

@siuc-nate ???

**Comment by siuc-nate** [comment]
We have been inconsistent (e.g. /resources/ is plural but /graph/ is singular), so either one should work.  I do agree that it should be `/envelope(s)/{ctid}` though.

**Comment by excelsior** [comment]
Yes, `/envelopes/{id}` is already taken—it retrieves an envelope by ID, not CTID:

https://credentialengineregistry.org/envelopes/5cebb332-eca6-4a2d-a82b-802f30cb5d6d

The endpoints under `/resources/documents/` all use CTIDs for manipulating envelopes (like deleting them or transfering them between organizations), that's why I suggested using a name like `/resources/documents/{ctid}`. But all of those APIs are private for obvious reasons, so it probably doesn't make enough sense to put a public endpoint into that lot after all…

**Comment by jeannekitchens** [comment]
@mparsons-ce this was opened in 2017.  Is this issue still open?

**Comment by siuc-nate** [comment]
I think our options are:
1. `/envelopes/{(ct)id}` - Would require some additional code changes to detect whether `{(ct)id}` is a GUID (for an envelope ID) or a CTID (which would return a collection of envelopes).  Probably bad form to do it this way.

2. `/resources/documents/{ctid}` - Means putting a public API endpoint in with a bunch of private API endpoints (maybe that's not so bad?)

3. `/envelope/{ctid}` - Would probably be okay (if a little easy to confuse with `/envelopes/{id}`)

**Comment by mparsons-ce** [comment]
I would suggest:
/envelope/{ctid}
or a more verbose but clear option:
/envelopeByCtid/{ctid}

**Comment by edgarf** [comment]
Decision: `/envelopes/{(ct)id} `

**Comment by excelsior** [comment]
@mparsons-ce This feature is available for testing on sandbox.

**Comment by mparsons-ce** [comment]
@excelsior I did some quick testing and this feature seems ready to promote.
Thanks.
