### ISSUE TITLE
Registering CEASN data in the staging CER from CASS.

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CredentialRegistry#161]
We are attempting to register data as follows:

1. Construct named graph containing competency framework in JSON-LD format, CEASN schema.
1. Construct signed envelope using server specific RSA 2048 key.
1. Post envelope to lr-staging.learningtapestry.com

Intermediate files and code will be attached showing the exact process.

Currently getting the following response:
```
    {
      "errors": [
        "405 Not Allowed"
      ]
    }
```

**Comment by Lomilar** [comment]
Competency Framework in named graph, and packaged as envelope.

[case-framework.ceasn.graph.json-ld.txt](https://github.com/CredentialEngine/CredentialRegistry/files/1471876/case-framework.ceasn.graph.json-ld.txt)
[case-framework.ceasn.graph.envelope.json-ld.txt](https://github.com/CredentialEngine/CredentialRegistry/files/1471877/case-framework.ceasn.graph.envelope.json-ld.txt)

**Comment by Lomilar** [comment]
Signing process (Enriched server-side javascript, edited for clarity)


```
	load("https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/8.0.4/jsrsasign-all-min.js");
	...
	var ceGuid = framework.getGuid();
	if (framework["ceasn:ctid"] != null)
		ceGuid = framework["ceasn:ctid"]
	else
		ceGuid = "ce-"+ceGuid;
	var envelopeGuid = ceGuid.replace("ce-","");

	var asnFramework = httpGet(cassEndpoint()+"ceasn"+cassInternalFrameworkId);

	// Creating JWT encoded package.
	var sHeader = JSON.stringify({alg: 'RS256', typ: 'JWT'});
	var sPayload = JSON.stringify(asnFramework);
	var prvKey = KEYUTIL.getKey(EcPpk.fromPem(cerPpk()).toPkcs8Pem());
	var sJWT = KJUR.jws.JWS.sign("RS256", sHeader, sPayload, prvKey);

	var package = {};
	package.envelope_id=envelopeGuid;
	package.envelope_type="resource_data";
	package.envelope_version="1.0.0";
	package.resource = sJWT;
	package.resource_format="json";
	package.resource_encoding="jwt";
	var result = httpPost(
		JSON.stringify(package),
		"http://lr-staging.learningtapestry.com/resources/"+ceGuid,
		"application/json");
```

**Comment by andersoncardoso** [comment]
A few errors I identified:
- the endpoint for POST is `/resources`. For PUT is `/resource/:id`. You're posting to `/resources/:id` (read [0] below)
- the resource doesn't have a `@type` (that's strictly needed, otherwise we couldn't know which json-schema to validate).
- you are not providing the `public_key` on the envelope
- the resource doesn't comply with the currently provided schema

[0] 
```
HTTP 405 Not Allowed
A request was made of a resource using a request method not supported by that resource; for example, using GET on a form which requires data to be presented via POST, or using PUT on a read-only resource.
```

**Comment by Lomilar** [comment]
Thanks for the info. I just discovered [this document](https://github.com/learningtapestry/metadataregistry/blob/master/docs/02_ce-registry_walkthrough.md) for publishing.

1. Cool, taken care of (edited above code).
2. Based on a number of conversations with Nate, Stuart, etc, I am now unsure as to the desired form to publish a framework along with its competencies. I was told a named graph would do. Can you provide or link to an example of what you uploaded for a framework and its competencies?
3. Cool, taken care of (edited above code).
4. The feedback the services give here is great.

Publishing is working, need to fix a few things, but here's a teaser.

http://lr-staging.learningtapestry.com/resources/ce-87ce57bb-eb40-377b-8319-8e1430bee7ac

**Comment by Lomilar** [comment]
Framework:
http://lr-staging.learningtapestry.com/resources/ce-b835c3a8-d745-35c2-afce-922b6ceab7ff
A competency in the framework:
http://lr-staging.learningtapestry.com/resources/ce-0bff4844-9b0e-3200-8282-415c2140102b

@siuc-nate @stuartasutton Does this look correct? The CER is able to maintain the canonical IDs and other values, which is nice, but it has that side effect of not being able to follow the @id to get the CEASN representation, one must instead use some sort of /resources/?id=<canonical URI> to get the CEASN form from the registry.

**Comment by andersoncardoso** [comment]
I'm using the following test samples:
https://github.com/CredentialEngine/CredentialRegistry/blob/master/db/seeds/ce_registry/competencies.json
https://github.com/CredentialEngine/CredentialRegistry/blob/master/db/seeds/ce_registry/competency_frameworks.json

One thing though, is that my sample's `@id` are just the uuids, and yours is the full uri, so for finding the competencies inside a framework you need to use that full uri. i.e: 
```
http://lr-staging.learningtapestry.com/ce-registry/competency/search?framework=https://case.georgiastandards.org/ims/case/v1p0/CFDocuments/6b049b04-4720-11e7-8d2d-b41056aae514
```
If we want to be able to reference this `framework=<some-identifier>` differently, I would need to know how exactly (just the uuid part at the end, or using the ctid, etc) 

Any questions let me know.

**Comment by siuc-nate** [comment]
@Lomilar Almost. A few things:

CompetencyFramework does not have a ceasn:hasChild property - this was a decision @stuartasutton made in https://github.com/CredentialEngine/vocabularies/issues/474 (specifically https://github.com/CredentialEngine/vocabularies/issues/474#issuecomment-333665400 ). 

Personally I do wish that CompetencyFramework retained a "hasPart" property to point to all of its children, but this would not seem to be in alignment with the way ASN works. @stuartasutton can explain better.  It could perhaps be the realm of a meta property (e.g., meta:hasPart), but discussion of that is beyond the scope of this thread.

As for the identifier: You make a good point about the `@id` thing, but short of making `@id` an array field, I do not have a good answer. We've had many discussions about this but I don't think we've ever settled on a _good_ solution.

The rest of it looks good to me.

**Comment by stuartasutton** [comment]
@siuc-nate is correct that that competency framework does not use the hasChild to list an inventory of all the competency. It lists only top nodes in a set of structured competencies using the hasTopConcept. And nothing like hasPart has been considered for such a full enumeration because there has never been a need for it in an RDF context.

I don't understand the identifier issue. The example is comprised of a set of envelops. Is this purely a Registry issue--the only place where an envelop matters?

**Comment by siuc-nate** [comment]
@stuartasutton The identifier issue, as I understand it anyway, is illustrated in the examples @Lomilar gave:
http://lr-staging.learningtapestry.com/resources/ce-b835c3a8-d745-35c2-afce-922b6ceab7ff
http://lr-staging.learningtapestry.com/resources/ce-0bff4844-9b0e-3200-8282-415c2140102b

If we are to follow our own conventions, the `@id` for both of those records should be the `credentialengineregistry.org/resources/_____` style of URI instead of the "real" URI under the `georgiastandards.org` domain. This is so that if someone resolves the `@id`, they are guaranteed to get a record from the registry (along with all of the benefits of conversion and data quality and so on that that implies).

However, this is potentially in conflict with the semantically "correct" URI, which _is_ the `georgiastandards.org` one.  So the question is, how do we retain a reference to the `georgiastandards.org` URI in such a way that it is clearly an alternative `@id`, while still enforcing a `credentialengineregistry.org` `@id` across all records in the registry? The record in the registry is effectively a copy of the record in the `georgiastandards.org` repository, but each record in each repository needs its own `@id`, so it's not clear whether or not it is correct to use `ceasn:derivedFrom` in this case, since it's just one record being copied and not (semantically speaking) any of the actual data (other than the `@id` field itself being modified, which in turn _may_ be enough to trigger a `derivedFrom`?).

Is it just a simple matter of using `sameAs`? Or do you need to do something like this?:

```
{
    "@id": [
        "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1ccc42-4720-11e7-9c3a-5226623e10ae",
        "http://credentialengineregistry.org/resources/ce-0bff4844-9b0e-3200-8282-415c2140102b"
    ]
}
```

I get the feeling that it's really really easy to overthink something like this.

**Comment by stuartasutton** [comment]
:-) I thought we had settled this many months ago. I wouldn't say you're overthinking, @siuc-nate; but, the solution is simple and should follow the pattern of the ASN:

1. Competency frameworks and Competencies in the Registry have **Registry URI** without exception and throughout; 
2. The ceasn:exactMatch property is used with each competency statement to hold the URI of the Georgia statement; and
3. The ceasn:source property in the Competency Framework node can be used to point to the Georgia framework URI; and, if it exists, a second instance of ceasn:source could point to an authoritative PDF etc. 

This is perfectly legit unless you are among the blinkered few who still think things on the web should have one authoritative URI :-)

We should have the means to export either (or both) the CER version (with source and exactMatch URI to the Georgia) **and** the Georgia version... Recall that the CER version is not worth much if you hand it back to Georgia for their uses for the same reason that led to this issue here ...the CER version on their website would be rather pointless since resolving any of its links would take the person or application away from the Georgia site and back to the CER. 

Stuart

**Comment by Lomilar** [comment]
Because of the rule that the CTID should only exist for a single version of the object (http://credreg.net/ctdlasn/terms/ctid#ctid), I'm finding that the CTID cannot be stored on a mutable object, and must be generated (or derived in my case from the versioned URI) every publish where the object has changed. 

This is similar to the behavior of an ISBN where each edition of the book has a different ISBN when published.

Just thinking of all the rules:

When an object is changed it should be derived from its last registered version.
When an object is changed its ceasn:exactMatch should be wiped.
When an object is changed, it substantively changes its parents, so this process should be repeated for every parent.
When an object is registered it should have a CTID created.

All relationships should be rewritten to refer to the Registry URI, except for URIs that are not in the registry? So, some exactMatches will be objects in the registry and some will be objects in different formats/schemas outside the registry, yes?

**Comment by siuc-nate** [comment]
@Lomilar While I agree that the documentation you reference would imply the issue you describe, I should note that this is **not** how we have been communicating the nature of CTID to our partners (nor is it how I understood CTID to operate - @stuartasutton did that comment get changed when we updated the definitions and such?)

The way we have been describing CTID is as a product identifier.  Multiple "versions" of a credential (e.g., updates to cost, fixing typos, etc.) would all share the same CTID, whereas semantically _different_ "versions" of a credential (e.g., different competencies or requirements, where one "version" could not be considered interchangeable with the other) would have different CTIDs.  It is in this usage that "version" is probably a poor choice of words, since it can mean different things when you get down to the details.

In this context, I would assume that each copy of a competency would have its own CTID (CTID2 -derivedfrom-> CTID1), but revisions to that competency by its owner would (or at least could) retain the same CTID.

To throw one more wrench into things: We have been explicitly telling partners that we leave it up to _them_ (the publishers of the data) to dictate when something does or does not qualify as needing a new CTID (e.g., when two "versions" are sufficiently different from one another).

@stuartasutton if you have anything to add, I would welcome it.

**Comment by stuartasutton** [comment]
@siuc-nate, @jkitchensSIUC, and all, the definition of CTID has had to change as we pushed it from a "product ID" for credentials to ID for 'everything'--latest being competencies. The change circumstances for some of these various entities are different and show-horning them all into a single rule for CTID change is neither likely nor useful. 

A CredentialOrganization can't logically have a "product ID" and would likely have the same CTID throughout most of it's history regardless of changes. Also, with Credentials, I thought we were drawing distinctions between "snapshots" for Credentials (tinkering/correcting/minor revision over time) and owner-declared "versions" that were considered different beasts from the version they supersede and worthy of a new CTID. Competencies present a whole different conceptualization of change from that of a Credential, or a LearningOpportunity, or an Assessment.

So, the problem for me with the general application of the CTID across all URI-identified entities in the registry is that ground rules for change for all those classes may not (probably should not) be the same. And the signals of change are different with different entities--obvious with some (Competencies) and not so obvious with others (Credentials). The "derivedFrom" with Competencies triggers an obvious change and to the extent a CTID on a Competencies plays any useful role, derived nodes would be assigned new CTID (replicating the signal already well covered by their change of URI).

**Comment by siuc-nate** [comment]
This is implemented.
