### ISSUE TITLE
Graph search returning 502 Bad Gateway or 301 Moved Permanently

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#185]
I finally had a chance to mess around with the graph search endpoint, and I haven't had much luck. Hopefully you can point out what I'm doing wrong (the tool used in the screenshots below is [Advanced REST Client](https://install.advancedrestclient.com)):

Using the example query from the [examples page](https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/graphql-examples.md):

```
{
  "query": "query searchCredentials($conditions: [QueryCondition]) { credentials(conditions: $conditions) { ctid name }}",
  "variables": {
    "conditions": [
      {
        "object": "Competency",
        "element": "description",
        "value": "robotics",
        "operator": "CONTAINS"
      }
    ]
  }
}
```
I have made POST requests (with the above in the body of the request) to the following:
https://credentialengineregistry.org/ce-registry/graph-search
https://credentialengineregistry.org/resources/graph-search
https://credentialengineregistry.org/graph-search
These all return 502 Bad Gateway. 
![image](https://user-images.githubusercontent.com/21346519/36177256-bf54b296-10da-11e8-85c7-1bb5b198598b.png)

Trying again with just http:// I get:
http://credentialengineregistry.org/ce-registry/graph-search
http://credentialengineregistry.org/resources/graph-search
http://credentialengineregistry.org/graph-search
These all return 301 Moved Permanently.
![image](https://user-images.githubusercontent.com/21346519/36177313-dfeb52a8-10da-11e8-83d4-25d478918145.png)

The documentation doesn't specify exactly what the URL should look like, so I'm not sure which of the 3 formats above (if any) are correct. I assume the body content type should be `application/json`, but I'm not sure if the request even gets far enough for that to matter. 

Has the graph search not been implemented on the production registry server?

**Comment by siuc-nate** [comment]
Following a suggestion from @cwd-mparsons I tried the sandbox. After a few different versions of the URL, I got something from 
https://sandbox.credentialengineregistry.org/graph-search

![image](https://user-images.githubusercontent.com/21346519/36177921-e7bcf3e0-10dc-11e8-9404-92f1a8da242e.png)

No data (not that I would expect any for such a specific query) but it would seem that it at least works - at least, in the sandbox.

**Comment by siuc-nate** [comment]
Slightly related question (perhaps it should be its own issue?), are there any examples of very general queries that should generally always return _something_? These would be a good starting point for learning the query structure, I think. 

For instance, the following (modified from example 3 on the [samples page](https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/graphql-examples.md)) returns no results, even though there are credentials of that type in the sandbox:
```
{
  "query": "query searchCredentials($conditions: [QueryCondition]) { credentials(conditions: $conditions) { ctid type }}",
  "variables": {
    "conditions": [
      {
        "element": "type",
        "value": "AssociateDegree"
      }
    ]
  }
}
```
For comparison, the results of https://sandbox.credentialengineregistry.org/ce-registry/search?fts=studies contain at least one associate degree. I also tried `ceterms:AssociateDegree` as the value of `value` but that didn't return anything either. 

![image](https://user-images.githubusercontent.com/21346519/36178519-b4259332-10de-11e8-922b-66007dc6d7fe.png)

Is there a documented table/list/graph/map/otherwise that translates between verbatim CTDL terms used in the schema/JSON-LD and the simplified versions that appear to be in use in the graph search? It would make it easier to generate queries if so - otherwise I need to guess at them if they aren't directly covered in the documentation. 

Or is it as simple as removing the prefix (generally "ceterms:" but not always)? There is a minute chance of name collisions (at least in theory) for cases where the term (sans its prefix) shows up more than once (for instance, [inputType:Business](http://credreg.net/ctdl/vocabs/inputType/Business) and [orgType:Business](http://credreg.net/ctdl/vocabs/orgType/Business), though the two are not used as values for the same property).  This may not be worth worrying about.

**Comment by rradonic** [comment]
Yes, making requests to http:// URLs always returns a 301 response, it's redirecting you to https://.

I'll see what's up with the 502 responses though, that shouldn't be happening.

**Comment by aspino** [comment]
@siuc-nate I'll try to address some of your questions below:

>  These all return 301 Moved Permanently.

As @rradonic just said, you need to use `https`, because the server redirects from `http` and many REST clients - like Postman and Advanced REST Client - seem to stop when they get the first response.

>  These all return 503 Bad Gateway.

You're not pointing to the right URL. The graph search is only deployed in sandbox. The right URL for sandbox is https://sandbox.credentialengineregistry.org/graph-search.

> I assume the body content type should be application/json, but I'm not sure if the request even gets far enough for that to matter.

Yes, the content type needs to be `application/json`. Please check the Postman collection for specific details about the requests.

> Is something delaying the implementation of this on production?

Honestly, I simply wanted to wait for the client to provide feedback to some of the questions and concerns I raised while development was talking place. This graph search can become really huge and complex, so I had to make some choices that maybe are right, or wrong, and so I thought waiting for the feature to be more mature and having time to discuss said choices seemed like the most sensible approach to me. However, nothing prevents the deployment to production, at least from a technical standpoint.

> Slightly related question (perhaps it should be its own issue?), are there any examples of very general queries that should generally always return something? These would be a good starting point for learning the query structure, I think.

The [Postman collection](https://www.getpostman.com/collections/0ab1eb6c89ade2a55c75), as well as the [examples page](https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/graphql-examples.md), have realistic queries. The problem is that the sandbox environment does not seem to contain enough data for the queries to return proper results. For example last time I checked there were no competencies. I'm happy to help you import into sandbox the data set I used to create the collection and the integration tests in my development environment, if you think that'll be helpful.

> For instance, the following (modified from example 3 on the samples page) returns no results, even though there are credentials of that type in the sandbox:

That's probably because those credentials don't match any of the paths considered as required. In the case of credentials, the paths are:
- `Organization > Credential`
- `Credential > ConditionProfile > CredentialAlignmentObject > Competency`
- `Credential > ConditionProfile > AssessmentProfile > CredentialAlignmentObject > Competency`
- `Credential > ConditionProfile > LearningOpportunity > CredentialAlignmentObject > Competency`
- `Credential > ConditionProfile > Credential > ConditionProfile > CredentialAlignmentObject > Competency`

If the credentials don't match at least one of these paths, even if they match the filters, they won't be returned as search results.

> Is there a documented table/list/graph/map/otherwise that translates between verbatim CTDL terms used in the schema/JSON-LD and the simplified versions that appear to be in use in the graph search? It would make it easier to generate queries if so - otherwise I need to guess at them if they aren't directly covered in the documentation.

The most noteworthy details about the current implementation are documented [here](https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/graphql-spec.md#current-implementation). In general, I tried to honor most of the naming already used in CTDL, but there are some minor differences, like the removal of the namespaces, or the fields with dashes in their names. Other than that names should match.

> Or is it as simple as removing the prefix (generally "ceterms:" but not always)? There is a minute chance of name collisions (at least in theory) for cases where the term (sans its prefix) shows up more than once (for instance, inputType:Business and orgType:Business, though the two are not used as values for the same property). This may not be worth worrying about.

You're right, the prefix is not used for the search. And we're aware that entities with the same name in different namespaces could become a problem. As a matter of fact, I asked for feedback on this topic a few months ago when we were developing the import feature. I'm copying here what I said then:

"I’m not preserving the namespaces when doing the import into Neo4j. This means you don’t need to specify the `ceterms:` prefix when you’re trying to reference a field or a value. I’m aware this can be problematic if we need to differentiate two or more fields that happen to have the same name and live in separate namespaces, but 1) what are the chances of this happening (I’ve never seen it in any document so far)? and 2) even if we need to take it into consideration I’d suggest just adding some way to optionally include the prefix (something like ‘ceterms__description’ to indicate that in this specific case we’re referring to the ceterms namespace, on an on-demmand basis. Not being forced to use the namespaces all the time I think fells so nice, but let me know what you think."

**Comment by siuc-nate** [comment]
Thanks, that's all very useful information. And I apologize for forgetting that you mentioned the namespace thing earlier. 

We can leave it on the sandbox for now - somewhere along the line I picked up the notion that it was already implemented on production, hence my confusion earlier. 

I do have one question though:

> That's probably because those credentials don't match any of the paths considered as required. In the case of credentials, the paths are:
>
> -`Organization > Credential`
> -`Credential > ConditionProfile > CredentialAlignmentObject > Competency`
> -`Credential > ConditionProfile > AssessmentProfile > CredentialAlignmentObject > Competency`
> -`Credential > ConditionProfile > LearningOpportunity > CredentialAlignmentObject > Competency`
> -`Credential > ConditionProfile > Credential > ConditionProfile > CredentialAlignmentObject >` 
> -`Competency`
>If the credentials don't match at least one of these paths, even if they match the filters, they won't be returned as search results.

Does this mean it's not possible to do a query that simply returns all credentials of a given type (or list of types) (or similar queries that don't really need to traverse a graph)?

**Comment by science** [comment]
> Does this mean it's not possible to do a query that simply returns all credentials of a given type (or list of types) (or similar queries that don't really need to traverse a graph)?

@siuc-nate - it might make sense to create `- Credential` search path - which doesn't link to any other objects - that would then return any attribute associated with the Credential, without traversing any other objects. I think this is easy to provide..

**Comment by siuc-nate** [comment]
It should be possible to find all top-level entities by some property/value(s) on the entity itself.

Does the GraphQL search handle full-text search like the other search method does?

What I'm trying to avoid is a scenario where we require third-party developers to learn and use two completely different types of search methods in order to get everything out of the registry.  I could understand the other search method not being able to do graph-like things, but the graph search should at least be able to do basic queries so that a developer only needs to learn, code for, and rely on the graph search for everything (if possible).

**Comment by siuc-nate** [comment]
Bonus points if you can fulfill this use case (not a priority, but relevant to the search):
During development/debugging, it's often useful to find credentials (and other entities) that have any value for a given field, without caring what that value _is_. 

For example, if we want to find "all credentials that link to a cost manifest", the query would be phrased something like "give me all credentials where ceterms:hasCostManifest is not null and has at least one value".  I don't care (at query time) what the value(s) are, I just want to do some testing/development that requires looking at credentials with cost manifests.

This probably isn't relevant for end-users, and whether or not developers down the line may find it useful is up in the air, but it's something that comes up on our team from time to time and we don't often have a good solution for it - especially in terms of "what's in the registry" versus "what's in our database".

If something like that is easy to implement while you're working on the other stuff, it would come in handy.

**Comment by aspino** [comment]
Unfortunately, it is not possible to specify custom paths in the current version.  However, I think it's important to differentiate a couple of scenarios:

1. If you search for credentials and filter them by attributes that are only related to credentials (which I think is what you're asking), then, as @science suggests, that could be added quite easily (I think), by building a separate query for this kind of scenario.
2. If you intend to run a query whose filters relate to other entities (what would be a JOIN in typical databases) then you're forced to specify a matching path in Neo4j, because otherwise you'd incur in cartesian products and performance would be terrible. Being forced to specify a path is fine, it's how Neo4j works anyway, and it's similar to building SQL queries and being forced to specify the tables involved. But in this case we're building the search queries dynamically, so creating this sort of custom paths, applying the filters, optimizing them, etc. on top of the current implementation would definitely be possible to implement but certainly not easy, and so was out of the scope for this first implementation.

Regarding the full text search, the current API supports basic comparison operators like `STARTS_WITH`, `CONTAINS`, etc. but fulltext indexes are not used. We'd have to use Neo4j's explicit indexes to achieve that.

**Comment by cwd-mparsons** [comment]
@siuc-nate Can this issue be closed?

**Comment by siuc-nate** [comment]
Yep.
