### ISSUE TITLE
Add @context to JSON schema

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#23]

**Comment by siuc-nate** [comment]
This has been added:
![image](https://cloud.githubusercontent.com/assets/21346519/24005310/ab8fe16e-0a36-11e7-95fc-a03ab5aa69b6.png)

Note that the schema documents now require `@context` at the root level.

I have used the patternProperties aspect of JSON schema here because anything could be in the `@context` block, provided its key is a string with no spaces and its value is a URI.  The regex for this requires an escaped backslash to be valid JSON; you will want to make sure your parser turns `^\\S+$` back into `^\S+$`.

I'm not well-versed in regex so there may be something more optimal.

**Comment by siuc-nate** [comment]
Actually, I just realized - the context needs to be a property of each of the top-level classes, not of the document root.

I'll fix it.

**Comment by leolara** [comment]
@siuc-nate 

`@context` gives a lot of flexibility to JSON-LD. But unfortunately JSON Schema does not allow that flexibility.

We have hardcoded namespaces in our JSON Schema, and hence we need to hard-code `@context``

What I would do is:

```js
// In definitions 
"@context": {
  "type": "object",
  "properties": {
    "ceterms": { "type": "string", "enum":["Put here ceterms vocab URI"] },
    // so on with all our namespaces
   },
   "additionalProperties": false
}
```

Then I would put a `$ref` in to that defintion in each `@context` property on the top-level entities.

I am not that sure about `additionalProperties`, perhaps we want people to use other namespaces for values?

**Comment by siuc-nate** [comment]
I thought the purpose of patternProperties in JSON schema was specifically to allow such flexibility (within constraints set by the regex pattern)?

However, I did a bit more reading, and it seems we would still set additionalProperties to false, then it would only allow anything that matched the pattern in patternProperties.

**Comment by siuc-nate** [comment]
In thinking about it some more, I suppose if we're being strict with the rest of the validation, then it's probably okay to hard-code the context into it as well.  I've updated the schema validation generator to add in the context as you described it @leolara

**Comment by leolara** [comment]
@siuc-nate 

JSON schema allows to describe a flexible `@context` object.

The problem is: if the user renames a namespace (which is allowed in JSON-LD using `@context`), there is no way to handle that in JSON Schema.

As it seems that we agree, and it has been implemented, I close the issue
