### ISSUE TITLE
Adding a PURGE option to do a physical delete of a record versus a virtual delete

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#232]
@science 
During a meeting at the end of May we discussed adding new function to the registry to enable a physical delete of record from the registry. I am adding this issue as a placeholder to ensure the need for this feature stays on the short term radar. 
This would be a function only available to authorized sources.

**Comment by science** [comment]
Adding @aspino.

Noting @cwd-mparsons and I discussed this recently, and I think we agreed that while the purge option is needed, the important feature is actually re-assigning CTIDs to new owners. 

We shouldn't purge a record and then recreate it, generating a new CTID (as that defeats the long-lived purpose of CTIDs). We should have an easy API way to enable a new owner to start updating an existing CTID. By way of analogy, in a filesystem, we just want to swap owners of a file.

Input welcome -- @siuc-nate you might have views on this! :)

**Comment by aspino** [comment]
@science I think I get what you mean, but when you talk about "change the owner", I guess that actually means changing the publisher, right?

From what I remember, every envelope that gets uploaded is signed with the publisher's key, and then stored. By looking at the code I also see you've added the option to "impersonate" an organization and sign on its behalf, but I'm not sure if that's too relevant here, because the organization stays the same, doesn't it?

I think the process could involve 2 steps:

1. Current publisher of the envelope (or an admin) invokes an API endpoint that accepts an envelope ID and a publisher ID that will be the new owner. When executed it would prepare the transfer by marking the envelope as ready to be transferred (with a flag or something of the sort).
2. New publisher can then invoke an API endpoint (perhaps it can be the same one that updates a resource) sending the envelope ID. The signature is then verified and, if valid, the envelope record is updated and re-signed to reflect the new publisher. The ownership transfer could be reflected as another update to the envelope, so previous history would be kept.

This is just a preliminary idea about the implementation, so feedback is welcome, but I'd like to know if you think this approach is aligned with what you had in mind for this feature or not.

**Comment by siuc-nate** [comment]
Should this be split into two issues? This one for the purge feature, another issue for reassigning identifiers/owners/etc.?

**Comment by cwd-mparsons** [comment]
I created #283 for the transfer ownership scenario. 
This issue will focus on a Purge feature.

**Comment by mparsons-ce** [comment]
Alex is going to use a similar approach as transfer:
- super publisher only
- just provide the CTID
- work with client keys and registry keys

**Comment by excelsior** [comment]
@mparsons-ce 

The endpoints are

```
DELETE /resources/documents/{ctid}?purge={true|false}
DELETE /{community_name}/resources/documents/{ctid}?purge={true|false}
```

The `purge` argument is optional and defaults to `false`. If a truthy value is provided, the document gets physically deleted along with its history, transactions, and dependent resources.

**Comment by excelsior** [comment]
It's available on sandbox (alongside the ownership transfer feature). The Swagger docs have been updated.

**Comment by excelsior** [comment]
@mparsons-ce Did you have a chance to test this feature?

**Comment by jeannekitchens** [comment]
@mparsons-ce this has been open since July of last year but looks as though there is a delete endpoint.  All resources published that are incorrect and not for archive purposes has to be purged.  please respond to this issue so it can be closed and any clean up handled.

**Comment by jeannekitchens** [comment]
@mparsons-ce per our meeting yesterday about published information that needs to be purged.  What's the status?

**Comment by mparsons-ce** [comment]
@excelsior I have completed testing this feature. Please promote the feature to production.
Thx

**Comment by mparsons-ce** [comment]
@excelsior 
I have been having errors doing a purge. I tried again today with:

https://sandbox.credentialengineregistry.org/resources/documents/ce-a86c6fb9-bf6b-436e-82bf-7850d1f13379?purge=true

I get the following error:
{"errors":["undefined method `purged_at=' for #\u003cEnvelope:0x00005557ebd6a360\u003e"]}

**Comment by excelsior** [comment]
@mparsons-ce For some reason, this feature was missing on sandbox. I fixed that. And also deleted the above envelope.

**Comment by jeannekitchens** [comment]
@mparsons-ce please update this issue ahead of this Thursday.

**Comment by mparsons-ce** [comment]
@excelsior The purge is working properly in the sandbox now.
