### ISSUE TITLE
Timeout issues publishing a ConceptScheme with a large number of concepts

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#242]
@edgarf 
I have been running into timeout issues when attempting to publish a concept scheme with 1452 concepts. The input file is under 2mb. I checked recently published documents and the next biggest file was under 1mb. 
I then tried fewer concepts, and progressively more until I ran into the timeout error:
- 100 concepts took 29 sec; 
- 200: 40 secs; 
- 300: 38 sec; 
- 500: 59 sec;  
- 750: 93 sec; 
- ~900 0r more result in a timeout error - after 100 seconds

Given that the payload is stored verbatim in an envelope and the latter is stored in the database, it is not clear why the publish step would so adversely be affected by a larger payload. 
Is the issue related to the slicing and dicing of the document parts?
If so, then maybe that process should be done after the simple save of the payload. 

I had been experimenting with parameters under my control to allow more time. I want to now check if the bottleneck occurs at the registry end somewhere.

**Comment by edgarf** [comment]
We will have this reviewed @cwd-mparsons

**Comment by excelsior** [comment]
@cwd-mparsons Yes, persisting an envelope's payload is pretty fast, it's extracting the resources from it that slows things down leading to a timeout.

Of course we can try increasing the timeout settings of the web server and the proxy server, but the best way of fixing this is storing the envelope immediately and processing its content in background.

This should be less of a problem on prod, since it's more productive than staging. Let us know if you're OK with implementing the above solution.

**Comment by cwd-mparsons** [comment]
Yes, I agree that  storing the envelope immediately and processing its content in the background would be a good approach. 
Thanks

**Comment by siuc-nate** [comment]
Will that present issues with error handling? If something goes wrong with handling the content of the envelope, the transaction will have already returned to the client (our system) by that point.

**Comment by excelsior** [comment]
@siuc-nate Good point. I'll investigate whether asynchronous processing breaks error handling and design an appropriate solution if this is a case.

**Comment by excelsior** [comment]
Looks like validation can be executed synchronously without causing a timeout. If the payload is valid, it will be persisted and the rest will happen in background. This way, the client will get a proper response.

This needs some additional testing, of course. @cwd-mparsons May I ask you to share some of the largest resources you have (preferably, in their original, not encoded form)?

**Comment by cwd-mparsons** [comment]
@excelsior I added a link to a payload file of a very large concept scheme file. This file is in CTDL JSON-LD, and so is the file that is sent to the registry API.

https://gist.github.com/cwd-mparsons/4b0cc62cb1357e126778d39aa943efe2#file-classificationcodes-json

**Comment by excelsior** [comment]
I deployed the background resource extraction feature to sandbox.

@cwd-mparsons The file above doesn't contain a valid JSON object. It looks truncated and contains real line-breaks (e.g. [line 782](https://gist.github.com/cwd-mparsons/4b0cc62cb1357e126778d39aa943efe2#file-classificationcodes-json-L782)). Am I missing something?

I fixed those issues and tried publishing that data, but it failed validation, because the `skos:ConceptScheme` schema is absent on sandbox. Do you always bypass validation when publishing stuff?

So I wasn't able to test the feature with a real problematic payload, but other files worked fine for me. Let me know if it works for you, thanks.

**Comment by cwd-mparsons** [comment]
@excelsior 
**re: Json**
I had copied this from an output file that had escaped quotes (\") and line breaks (\n\r). I tried to clean these up but clearly missed some. 

**re: Validation**
Yes, we always skip validation. The JSON validation schemas were getting very complicated. The API currently is responsible for producing the proper JSON-LD file. 

**Publishing**
However, I was able to publish the full file. The elapsed time was about 60 seconds. 
Actually I did it twice, the first time took 43 seconds, with a little less data per concept, and 57 seconds with all the data for the 1452 concepts. 
Is this time reasonable for the amount of data, or is there more optimization possible?

**Comment by excelsior** [comment]
It definitely is faster for me. This is happening on sandbox, right? Which endpoint are you using BTW? Perhaps I'm testing the wrong one…

**Comment by edgarf** [comment]
@cwd-mparsons  could you please review the above?

**Comment by cwd-mparsons** [comment]
The endpoint is for publishing a concept scheme:
https://credentialengine.org/sandbox/ConceptScheme/publish
