### ISSUE TITLE
Need a process to check if the search index is active and to be able to restart without learning tapestry resources

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#244]
@science  @edgarf @excelsior 
We had another problem today with data added July 19, 2019 that was not found in the search index.
Is there a public URL that we could use to check if the index is running? If not, could a process be added?

As well, could a process be added that allows credential engine admin staff to be able to restart an index that has stopped?

**Comment by edgarf** [comment]
This is currently done for Gremlin, we will attach a process for SPARQL as well.

**Comment by siuc-nate** [comment]
LT team will move this forward:
- Determine how to enable CE team to handle these situations
- Create documentation
- Implement necessary features
- Stability testing

**Comment by siuc-nate** [comment]
@edgarf What is the status of this for the SPARQL index and any other related services?

**Comment by excelsior** [comment]
@siuc-nate We haven’t had the need to restart the Neptune instance for a very long period. IIRC one of the previous versions of it didn’t perform well under load and required a restart in order to function well, but that doesn’t appear to be an issue anymore.

And the Neptune instance is always running, that’s one of the advantages of a cloud service. Having an API for checking its status doesn’t seem to be necessary.

I think implementing some consistency checks should be enough.

**Comment by siuc-nate** [comment]
Removed this from high priority because it hasn't been a problem for some time now.

**Comment by jeannekitchens** [comment]
@edgarf @excelsior this is part of a larger set of documentation and instructions that we need.  I removed high priority from this but we still need to address this.

**Comment by siuc-nate** [comment]
@excelsior will post details about a suggested solution to the current issue of the SPARQL index occasionally hanging/slowing down.

**Comment by excelsior** [comment]
@mparsons-ce @siuc-nate 

I implemented an API for controlling the state of the AWS resources powering the API and graph search.

The endpoint is `https://rgtpyiad2m.execute-api.us-east-2.amazonaws.com/cer/RemoteControl`.

You can check the status of all resources of a certain envirnment at once:

```
POST https://rgtpyiad2m.execute-api.us-east-2.amazonaws.com/cer/RemoteControl

{
    "auth_token": "<auth token>",
    "method": "status",
    "env": "production"
}
```

This will return a response like this:

```json
{
    "api": {
        "instance_id1": "running",
        "instance_id2": "running"
    },
    "neptune": {
        "cluster_id": "available"
    }
}
```

You can stop an instance by passing its ID:

```
POST https://rgtpyiad2m.execute-api.us-east-2.amazonaws.com/cer/RemoteControl

{
    "auth_token": "<auth token>",
    "method": "stop",
    "id": "instance_id1"
}
```

Please keep in mind that an instance doesn't stop immediately, especially in the case of Neptune. It goes from `running` (or `available`) to `stopping`, until it's `stopped`. It must be fully stopped, before you can start it again:

```
POST https://rgtpyiad2m.execute-api.us-east-2.amazonaws.com/cer/RemoteControl

{
    "auth_token": "<auth token>",
    "method": "start",
    "id": "instance_id1"
}
```

Regardless of the environment, use the production auth token in order to access this API.

Please let me know whether this will suffice your needs.

**Comment by siuc-nate** [comment]
It sounds like it should, but it will be hard to know for sure unless/until we need to use it someday.

I'm good with closing this issue in the meantime if nobody else objects.

**Comment by mparsons-ce** [comment]
This information needs to be documented in the registry how-to 'handbook'.

**Comment by edgarf** [comment]
Let's only leave the instructions that are actual at the moment.

**Comment by siuc-nate** [comment]
Per @excelsior this issue is no longer applicable due to changes in the architecture.  As long as the Registry is running, the search will be available.
