### ISSUE TITLE
Some queries seem to crash the search index

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#245]
It seems that some queries can cause the index to fail, and subsequent queries either prolong the failure or experience it for some short amount of time before the index recovers.

I can reproduce this with the following steps via: https://credreg.net/quickstart/queryhelper but it is not entirely consistent. 

Using the buttons in the first column:
1. Do a search for Certificates
- Receive results
![image](https://user-images.githubusercontent.com/21346519/61743640-574ffd80-ad5b-11e9-8d13-4bf2a1a6ce70.png)

2. Do a search for Certificates or Certifications
- Receive results
![image](https://user-images.githubusercontent.com/21346519/61743705-72bb0880-ad5b-11e9-9a9b-659fd071fe41.png)

3. Do a search for Any/All Credentials
- Receive 500 error (but not always - it may fail if you try it again immediately after receiving results)
![image](https://user-images.githubusercontent.com/21346519/61743757-8a928c80-ad5b-11e9-8baf-b50a7b3094ef.png)

4. Immediately (within ~0-5 seconds) do another search for Certificates
- Receive 500 error
![image](https://user-images.githubusercontent.com/21346519/61743948-d0e7eb80-ad5b-11e9-9b41-fab0cee0ab15.png)

5. Immediately do another search for Certificates or Certifications
- Receive 500 error
![image](https://user-images.githubusercontent.com/21346519/61744026-f8d74f00-ad5b-11e9-8d2a-add013ba9241.png)

6. Wait ~5-10 seconds

7. Do a search for Certificates
- Receive results
![image](https://user-images.githubusercontent.com/21346519/61744074-0ab8f200-ad5c-11e9-84b0-cacc11abe710.png)

etc.

Is there some way to log whether or not the process is dying while performing this experiment?

**Comment by siuc-nate** [comment]
Could this have had something to do with the index being rebuilt?

**Comment by excelsior** [comment]
Yes, indexing does affect the server's performance. Heavy queries running in parallel during that process may time out.

I changed the `/gremlin` endpoint to return 504 instead of 500 when a timeout occurs.

Also, even though the issue is aggravated by the index being rebuilt, it can possibly happen with no indexing in progress.

We can't get rid of the timeout setting completely, since we'd still like to interrupt a query execution if, say, it contains an infinite loop or just takes an enourmous amount of time to complete for some other reason.

But we can:

- increase the timeout (currently it's 10s),
- throttle the queries on our side.

**Comment by siuc-nate** [comment]
Is it possible this is related to the recent findings with regard to .not() and .union() causing timeouts?

**Comment by excelsior** [comment]
The server's performance sags during indexing, so the heavier a query the more likely it'll time out and affect lighter queries running alongside.
