### ISSUE TITLE
Develop process to secure the navy community

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#270]
There is a requirement to be able to lock down the navy community on the staging server. 
There is some (or will be) data that has a limited distribution type.
The publishing flow requires an apiKey. We would now like to control the consuming workflows, including:

- /navy/resources
- /navy/graph
- /navy/envelopes
- /navy/search

One approach would be to require an apiKey. However we don't want the registry to have to manage apiKeys. 
- We could provide an endpoint to validate an apiKey. 
- When an apikey is passed in the header, the registry could call the new endpoint to do the validation.

Another suggestion was to make use of private/public keys - not sure how this would work.
Is there a better approach?

**Comment by siuc-nate** [comment]
Some of the data in the navy registry (like vocabularies, credentials, etc) will need to be openly accessible as it is with the current credential registry (e.g. get by URI without an API key).

We also need to consider that the current use case is only for data that is limited by its distribution statement rather than something more sensitive or classified - we'll need to handle the latter as well.  I assume the navy will want to run their own instance of the registry for that, which leads me to this alternative proposal:

Two navy registries:
- One open as it is now (still requiring permissions to publish of course) and 
- One that is completely locked down from end to end.  

That should solve the current problem and also handle any other cases where records need to be secured.  It would also make it easier to hand an entire data store off to the navy down the road if they want it instead of trying to surgically extract certain secure records (and I would suspect it may be easier to maintain two distinct systems than one that tries to handle both use cases anyway) but that's just me speculating at this point.

**Comment by edgarf** [comment]
@siuc-nate @cwd-mparsons, thanks. @excelsior will research this issue.

**Comment by excelsior** [comment]
The API key approach is the best one IMO. We already have an authorization mechanism used for publishing and performing admin stuff. We can extend it to lock the Navy community down with little effort by introducing a Consumer user (in addition to Admins and Publishers). If key management is undesirable for some reason, we can offer a pre-shared token for accessing the Navy resources.

Even if the task boils down to isolating the Navy community into an independent registry, the above will be the best way to secure the entire server.

Of course, if only a handful of resources should be secured, then things will get more complicated as we'll need a way to assign resources to consumers who can access them.

I'm not sure what will be the purpose of having an endpoint for API key validation, though. Any restricted endpoint (e.g. `GET /navy/search`) will essentially be such an endpoint, because it'll return 200 or 401 depending on whether the key is valid or not.

**Comment by cwd-mparsons** [comment]
We didn't want the registry to have to manage apiKeys.
Currently all organizations that want to publish to the registry have to be approved in the account site. Once approved, an apiKey is assigned. The latter is used to retrieve the registry  (private on the account site) key. We were thinking that:
- a user would have to include the apiKey in the header for all GET requests
- the registry would validate the apiKey by calling a 'ValidateApiKey' endpoint in the related accounts site (see below for an example)
- if the endpoint returns false, reject the request
- if the endpoint returns true, allow the request
- the registry could cache the result (i.e. apiKey_XXXXX is valid). Then for future calls within a specified time period, the registry could just check the cache for the apiKey. If found in the cache, allow the request without having to call the 'ValidateApiKey' endpoint. 

**Example**
I am not sure it will be necessary to include a password/token to call the api - I will remove it if it doesn't make sense to include it. 

http://staging.credentialengine.org/accountsAPI/Organization/Organization/ValidateApiKey?password=????&apikey=2cd8ee22-ad68-4c0b-b268-e80c006b62c4

**Comment by siuc-nate** [comment]
We are also looking at an approach where rather than maintain two navy registries/communities, we just have one, but lock it down as described above.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @excelsior where is this.  We need this ASAP.

**Comment by excelsior** [comment]
The feature is deployed to sandbox and staging. API keys are supposed to be passed in the `Authorization` header (similar to the secured endpoints), e.g.:

```
Authorization: Token 2cd8ee22-ad68-4c0b-b268-e80c006b62c4
```

Validation results are cached for 1 hour.

**Comment by cwd-mparsons** [comment]
@excelsior 
We have now set up the sandbox environment. 
Please update the registry **sandbox** environment to use the following endpoint: 
https://sandbox.credentialengine.org/accountsAPI/Organization/ValidateApiKey?apikey=2cd8ee22-ad68-4c0b-b268-e80c006b62c4

**Comment by excelsior** [comment]
@cwd-mparsons Done.

**Comment by jeannekitchens** [comment]
@mparsons-ce @siuc-nate this should have been implemented with the Navy Community.  Review and close this issue.

**Comment by mparsons-ce** [comment]
@excelsior 
Please implement locking down the navy community on the staging server.

**Comment by excelsior** [comment]
Sure, what's the endpoint for validating API keys for staging?

**Comment by mparsons-ce** [comment]
https://staging.credentialengine.org/accountsAPI/Organization/ValidateApiKey?apikey=2cd8ee22-ad68-4c0b-b268-e80c006b62c4

**Comment by excelsior** [comment]
Done, please check.

**Comment by mparsons-ce** [comment]
I did some tests and the process is working as expected - closing.

**Comment by jeannekitchens** [comment]
@mparsons-ce you indicated this is working and you're closing.  Please close or indicate issue if still open.
