### ISSUE TITLE
Registry configuration files

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#275]
We need documentation related to configuration files for all communities, current and future:
- File name
- Description
- The nature of the data
- Example data

We need this for:
- Configuration file for communities
- Configuration file for JSON-LD contexts
- Configuration file for top-level classes
- Any other configuration files

We also need any information/configurations that are specific to individual communities (e.g. the Navy community).

We need to know if files that retrieve data cache/store that data, and for what length of time (e.g. does the system that retrieves JSON-LD context data do so on-demand, daily, weekly, etc.?)

We need to be able to generate all of the information to fill out these configuration files so that we know what you need and are able to provide it without a manual process.

**Comment by mparsons-ce** [comment]
@excelsior @edgarf 
We have an upcoming addition to CTDL for Rubric. 
This will be a good opportunity to produce and 'test' procedures for what has to be added updated for additions/updates to CTDL.

**Comment by excelsior** [comment]
@mparsons-ce 

Two kinds of changes are needed:

- The new class should be added to the configuration file (for every community it'll be used with). E.g. [ce_registry.json](https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/configs/ce_registry.json). So, `Rubric` needs to be added into the config's value map. In order to make the full-text search mechanism index find `Rubric` resources, an `fts` entry for the class should be added into the config. The latter step is optional.
- The new class' schema needs to added into the DB (again, a separate schema per community). The schemas are kept in the repository for reference: [schemas](https://github.com/CredentialEngine/CredentialRegistry/tree/master/fixtures/schemas). We don't have a CRUD for managing schemas yet, so a new schema should be promoted manually.

**Comment by mparsons-ce** [comment]
@excelsior 
Related: how to indicate that ‘child’ classes are to be top level objects

For example: for Pathway, both PathwayComponent and ComponentCondition should be top level resources - that is, reachable by https://credentialengineregistry/resource/ce-....

Is the only step to achieve the latter to add a class definition to the schemas?

**Comment by excelsior** [comment]
Adding a definition for a child class should certainly do the job. I couldn't find any other way of achieving that. Do you see any downside of having defiinitions for subclasses?

**Comment by jeannekitchens** [comment]
@mparsons-ce @siuc-nate please respond https://github.com/CredentialEngine/CredentialRegistry/issues/275#issuecomment-591419985

**Comment by edgarf** [comment]
This will be started after SPARQL related work is finished.

**Comment by mparsons-ce** [comment]
Alex created a starting document:
https://docs.google.com/document/d/1mQRZVzXHaZaCYzJLEvASP9uIPsTQthvYlRCp-_CrRLs/edit#

**Comment by edgarf** [comment]
@excelsior a bit more info with step by step instructions would be useful.

**Comment by siuc-nate** [comment]
This seems related to #289 - @edgarf @science what is the status of this and how does it relate to that issue?

**Comment by excelsior** [comment]
Promoting config changes is easy: since those belong to the repo, simply deploying them to the right environment will do the job. The FTS index has to be rebuilt if the FTS configuration was changed or resources with added types were published before the config changes have been promoted. A crucial thing here is making sure that the the config is valid, otherwise the app won’t function properly.

As I mentioned in #289, if schemas updates aren’t relevant anymore, that’s the only configuration thing we should care about.

**Comment by siuc-nate** [comment]
See #289 instead.
