### ISSUE TITLE
Document how to add public keys to be able to update the JSON Schema  and publish resources through the API

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#32]

**Comment by andersoncardoso** [comment]
Just to give a historic background on this: 
since the beginning one of the requirements was keeping the schemas and everything visible and tracked on the repo, so we could handle all via git, a simple commit away from deploy. 
The authorized public keys, for updating a schema, are inside `config/authorized_keys`.
The check is made before we decode the resource token on
https://github.com/CredentialEngine/CredentialRegistry/blob/master/app/models/envelope.rb#L120-L122

This is referenced on the docs here: https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/08_schemas.md
`For encoding this resource and sending the envelope you **have to use an authorized key**, i.e, you need to send the **public key** before to us, so we add it to the whitelist.`

**Comment by leolara** [comment]
@andersoncardoso and for publushing resources, are those the same public keys?

**Comment by coffeejunk** [comment]
@leolara that appears to be the case

**Comment by coffeejunk** [comment]
Unless I'm missing something, the only way to add a public key is to add it to the repository and re-deploy.

**Comment by leolara** [comment]
@coffeejunk please, document it somewhere in markdown

**Comment by coffeejunk** [comment]
> and for publishing resources, are those the same public keys?

To clarify, resources can be published with any public key by any arbitrary user. Only JSON Schema updates are validated against our internal list of known keys.

Subsequent updates to the resources however can only be made with the original key.

**Comment by leolara** [comment]
@coffeejunk Please document that last thing in markdown if it is not clear there
