### ISSUE TITLE
Create an API endpoint to list documents owned by an organization.

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#384]
@excelsior 
The API endpoint to delete a registered organization will fail if the organization owns any documents. However there is no means to determine which documents are owned by an organization. 

We would like a new registry API endpoint to list documents owned by an organization.

**Comment by excelsior** [comment]
@mparsons-ce Should the new endpoint be secured (i.e. require an auth token)?

**Comment by excelsior** [comment]
@mparsons-ce 

The endpoint is `GET /metadata/organizations/{organization_id}/envelopes`, it's available on sandbox. Doesn't require authentication for now. The response is paginated, because some organizations own a lot of documents. More details in [Swagger](https://sandbox.credentialengineregistry.org/swagger/index.html).

**Comment by excelsior** [comment]
The endpoint is available on production.

**Comment by siuc-nate** [comment]
@mparsons-ce Tested this on production and it is working.
