### ISSUE TITLE
We need a spec at the root of  the JSON Schema,

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/CredentialRegistry#4]
per: @leolara
Another important point is that currently, we do not have type spec at the root of  the JSON Schema, and hence the schema will not validate anything concrete. We only have auxiliary definitions.

I think for each entity we will have a JSON schema, that is basically what you have with all the definitions but a title and $ref in the root.

So for example for the JSON Schema of ceterms:CredentialOrganization we would have:

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "ceterms:CredentialOrganization",
  "$ref": "#/definitions/meta:CredentialPersonID",
   "definitions": { // all the defintions we have already in the common JSON schema }
}

That way we can reuse the work you have done populating definitions, and getting each entity validated separately. Alternatively we could do:

{
  "$schema": "http://json-schema.org/draft-04/schema#",
   "definitions": { // all the defintions we have already in the common JSON schema },
   "anyOf": [
       { "$ref": "#/definitions/meta:CredentialPersonID" },
       { "$ref": "#/definitions/meta:QACredentialOrganizationID" },
       // $refs to the rest of the 41 entities
    ]
}

That way one document will validate all entities, but I think perhaps it is more confusing for the user.

**Comment by siuc-nate** [comment]
I'm not sure I understand:
1. The schema already has a type spec, unless that is too broad:
![image](https://cloud.githubusercontent.com/assets/21346519/23757402/5b8319f0-04ac-11e7-96e7-d696a4b65231.png)

2. Are you saying we would have many copies of the same JSON schema document (including all classes and properties), just with a different title and $ref properties? Or would each be scoped to its relevant classes/properties? I would prefer the second approach.

**Comment by leolara** [comment]
@siuc-nate 

re1

as far as I understand the JSON Schema you are describing would validate against any JSON that is an object, independently of their fields or whatever else. Because there is not a properties, AdditionalProperties false or required, any object is valid with respect to this schema.

The $ref works as an include, so if you put $ref in the root it will bring the properties of the refered into the root schema, and then it will validate only the object with the properties of the referred schema.

re 2. What you prefer it is better, it just more worked. I offered to keep definions the same in all the entities and just $ref to the entity in the root in order to save you time. But, it will be more confusing to the developer as there are schemas defined that will not be used

**Comment by siuc-nate** [comment]
I think I understand what you mean.  I've updated the code to include the specified class if there is one, otherwise it includes all classes.

Compare:
http://credreg.net/ctdl/schema/validation/CredentialAlignmentObject/json one small class
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json one large class
http://credreg.net/ctdl/schema/validation/json all classes

Note that indicating a specific class will only include that class as a type; however, it will still walk the graph of CTDL to determine every class and property that needs to be included (ie the embedded/subclasses)

It is of course simpler to just always include everything.  A lot simpler, actually.  But, I already wrote the code to walk the graph, so I figured I might as well use it.

**Comment by leolara** [comment]
@siuc-nate 

The value of type is always a string or an array of strings of primitive values.

I think it should be like this:

```js
{
  "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
   "$ref": "#\/definitions\/ceterms:CredentialAlignmentObject",
   "definitions": {

...
```

There is no need to have type in the root as $ref is pointing to a object that has type, so all the properties in #\/definitions\/ceterms:CredentialAlignmentObject are imported into the root thanks to $ref.

$ref acts as an include, as far as I understand.

**Comment by leolara** [comment]
@siuc-nate 

Also, it is my understanding that the one with all classes, has no use, as it validates any object. As it does not offer any constrains on the JSON
