### ISSUE TITLE
Missing connections in Description Sets

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#400]
This credential:
https://credentialengineregistry.org/ce-registry/resources/ce-be376139-01a8-43dd-af56-834f7039bb70

References competencies from this framework:
https://credentialengineregistry.org/graph/ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b

But the description set for that framework:
`https://credentialengineregistry.org/description_sets/ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b`

Does not include that credential:
![image](https://user-images.githubusercontent.com/21346519/104204309-bf345100-53f2-11eb-88e4-6d5b9216ae4d.png)

There are other credentials that were recently updated to reference the same framework, but they also are not showing in the description set.  

Did the process that builds description sets fall over again?

**Comment by excelsior** [comment]
@siuc-nate The problem here is that the DS paths are evaluated in one direction. Description sets get pre-calculated when the envelope is published, and only the subresources present in the registry at that moment get included. In this particular case, the framework was updated on July 7, 2020. But the credential was published only yesterday (January 11, 2021) and wasn't included into the description set retroactively.

**Comment by siuc-nate** [comment]
Is this fixed and on production?

**Comment by excelsior** [comment]
@siuc-nate Yes and yes.

**Comment by siuc-nate** [comment]
I will test and close this.

**Comment by jeannekitchens** [comment]
@siuc-nate us this issue still open?

**Comment by siuc-nate** [comment]
The credentials now show in the description set for that framework.  Thanks.
