### ISSUE TITLE
Mismatch in total number of competency frameworks

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#418]
We are currently detecting the following:

- A count of 763 competency frameworks according to the registry's full-text search
- A count of 762 competency frameworks according to the SPARQL index

According to @mparsons-ce the last relevant change here is that two frameworks were published yesterday (3-23-2021).

A count of frameworks retrieved earlier today showed 766 competency frameworks.

How many frameworks do we really have, and why are the numbers different?

**Comment by excelsior** [comment]
@siuc-nate 763 is the correct number. One of the newly published frameworks failed to get indexed due to a new error which I'm still investigating. Hence the SPARQL search was showing 762 records. A full reindexing has fixed that.

I'm not sure about the 766 number. There are 796 frameworks if we include the deleted ones, but those aren't showed anywhere.

**Comment by jeannekitchens** [comment]
@siuc-nate @mparsons-ce the Finder search shows 763 competency frameworks.  Per @excelsior this number is correct.  The 766 shown with reports is incorrect.  Where is the 766 coming from?  

![image](https://user-images.githubusercontent.com/20917206/113314657-62de2080-92c1-11eb-8f72-1e8bb4f4f158.png)

**Comment by jeannekitchens** [comment]
All the Credential Finder and the competency frameworks report both show 762 frameworks.  
![image](https://user-images.githubusercontent.com/20917206/119579077-8c23a600-bd72-11eb-9a6e-2b0496cb81ac.png)
![image](https://user-images.githubusercontent.com/20917206/119579114-9e9ddf80-bd72-11eb-8f62-356837979baa.png)

Confirm there's 762 frameworks in the Registry so we can close this issue that's been lingering since March.

**Comment by mparsons-ce** [comment]
Yes, both the graph search and FTS search show 762.
