### ISSUE TITLE
Missing competencies from framework description sets

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#446]
The description sets for these frameworks (and others) on sandbox are missing a reference to their competencies:
https://sandbox.credentialengineregistry.org/graph/ce-b3485f5b-f90a-422c-99f7-8901cffa5556
https://sandbox.credentialengineregistry.org/graph/ce-d3913e58-b578-42be-8c8e-a55c0b66f5ab
https://sandbox.credentialengineregistry.org/graph/ce-85ea2bf0-b0a3-422c-9074-14f2efe51480

What would cause this to break?  The competencies do indicate that they are `ceasn:isPartOf` their respective frameworks.
![image](https://user-images.githubusercontent.com/21346519/117744655-bac84b00-b1ce-11eb-93d6-1f027f3c8271.png)

**Comment by excelsior** [comment]
@siuc-nate I recalculated the description sets on sandbox, and now the data looks good. The above frameworks were published a few months ago, and the description sets haven't been rebuilt  on sandbox since then. So maybe something was off back then, but now that mechanism appears to be working as expected.

**Comment by siuc-nate** [comment]
Thanks, good to know.
