### ISSUE TITLE
CRITICAL: Production full text search not returning expected numbers

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#453]
@excelsior 
I did the following search for organizations:
https://credentialengineregistry.org/ce-registry/search?resource_type=organization&page=1&per_page=20&sort_by=updated_at&sort_order=dsc

I only get back **264** records.
Using the graph search there are **727** for ceterms:CredentialOrganization and 33 for ceterms:QACredentialOrganization.

Credentials
The following only returns a total of **7010** records and there are over 23000
https://credentialengineregistry.org/ce-registry/search?resource_type=credential&page=1&per_page=20&sort_by=updated_at&sort_order=dsc

Other
Assessment: FTS: 359, graph: 582
LearningOpportunity: FTS: 258, graph: 483
Frameworks: 136 vs. 762

**Comment by excelsior** [comment]
Recently, we've updated FTS to only look for top-level resources when doing a type match: https://github.com/CredentialEngine/CredentialRegistry/issues/429#issuecomment-824966253

The majority of the resources with the above types are not top-level ones, hence the discrepancy. I can revert this change while we're thinking about a better solution. Let me know you're OK with that.

**Comment by mparsons-ce** [comment]
Why would not all of the organizations and credentials not be top level resources?
The resource_type of credential is an alias for all of the credential types.
For now, yes, revert the change to the old approach.

**Comment by excelsior** [comment]
@mparsons-ce The change has been reverted.

> Why would not all of the organizations and credentials not be top level resources?

Because they were published that way. Take a look at this envelope, for example:

https://credentialengineregistry.org/envelopes/ce-af83ed71-4051-d71e-26b4-a84bcc5134d1

Its top-level resource is a credential (an associate degree to be more specific), but it also contains a couple of organizations. When doing FTS the old way, both organizations are returned wrapped into the envelope (which has a credential type). Doing FTS the new way, nothing will be returned, b/c the envelope's type doesn't match the condition specified.

Here's a full list of organizations alongside their respective top-level resource's type:

[organizations.csv](https://github.com/CredentialEngine/CredentialRegistry/files/6532097/organizations.csv)

**Comment by mparsons-ce** [comment]
@excelsior 
The FTS uses resource_type to allow the use of an alias like credential, rather than having to specify all of the credential subtypes.
Can this alias be used for the envelope type? 
If not, then is there another solution?

**Comment by excelsior** [comment]
@mparsons-ce

> Can this alias be used for the envelope type?

I'm not sure I understand this solution.

Each envelope has an `envelope_ctdl_type` property, which equals to the `@type` of its _first_ resource. Of course, there can be resources of other types in that envelope, and those can be returned by the FTS if their type matches the provided `resource_type`. However, the found resources are not returned individually. Rather, the whole envelope is returned. And its type may be different, because the first resource from its `@graph` might not match the `resource_type` param.

Are you suggesting to override the `envelope_ctdl_type` property with the `resource_type` param's value? That'd be inconsistent with what the envelopes API returns.

>  is there another solution?

We can return resource instead of envelopes. That'd be a breaking change, but the approach would be less confusing.

**Comment by mparsons-ce** [comment]
The main issue was that the ctdl type on the envelope can’t use the alias. I will close this for now.
