### ISSUE TITLE
Frameworks missing SPARQL index again

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#455]
This framework was published on 2021-05-26:
https://sandbox.credentialengineregistry.org/graph/ce-e97b5d15-964f-4abd-94ef-22057ce7b300

However, it hasn't yet shown up in the SPARQL index:
![image](https://user-images.githubusercontent.com/21346519/120022159-9ed7ee00-bfb1-11eb-9161-74d1558f1a72.png)

There are other frameworks affected as well.

@science @excelsior How can we stop this from happening? It's a recurring issue every so often.

**Comment by science** [comment]
Adding @edgarf to the thread. I've discussed with @excelsior and @rsaksida about having a testing system that will detect when this fails, as it seems like it happens so often that we need a kind of "data uptime monitor" to watch for this issue ourselves, rather than just code fixes for the problem when the failure occurs, but of course we need to do that too.. 

Input welcome from RM and Alex if this doesn't seem like the right strategy. Thanks for creating a ticket, so we can use this to track progress towards various fixes (please edit or revise these as appropriate):

- [ ] Fixing / restoring the immediate failed frameworks
- [ ] Identifying cause for failure and coding solutions to make it more robust
- [ ] Adding data monitors that watch in the database for missing data that we can calculate as "should be present, but isn't." This might be probabilistic stuff (like min/max ratios for various elements that are expected to be linked together, or it might involve existing data graph sets that we use in the database that have known properties that are unlikely to change, to catch particular issues).

**Comment by excelsior** [comment]
@siuc-nate The background processing service failed on May 26, and ~2,100 jobs haven't been processed since then. I've restarted the service and the index is going to be good again soon.

**Comment by siuc-nate** [comment]
@science
Would this best be done as some kind of event-driven thing (when something is published, kick off a process that will wait a bit and then query the SPARQL to see if that record was added) or perhaps some kind of polling mechanism (every x minutes, query SPARQL for the IDs of the records that were published since the last check)?  Normally it seems like this should be a part of error handling (try to index something in SPARQL and if it fails, do something about it - no secondary monitoring needed) but I don't know you codebase at all so I'm not sure what's in place currently.

@excelsior 
Any way to tell what causes that process to fail?  Is it an error? A resource limitation? Something we should ask AWS about?

**Comment by science** [comment]
@siuc-nate - I like that idea of basically "log reconciliation" -- where we notice the requests going into the index and then later look for them with a separate process. That would be one viable approach for the third checkbox on my list, and one that might be simpler to implement than what I proposed.. +1

**Comment by siuc-nate** [comment]
That separate process would probably need to be able to check more than once in order to avoid throwing a false error if a particularly big record is taking a while to index (but hasn't actually failed).  Though it would also probably need some kind of maximum amount of patience (number of checks and/or amount of time since the first check) before it raises a notification regardless (in case the indexing process gets stuck and never logs that it succeeded or failed).

**Comment by siuc-nate** [comment]
Closing this, since the SPARQL index will be replaced by the new search
