### ISSUE TITLE
Missing description set for framework

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#482]
In sandbox:

The description set for this framework is missing:
https://sandbox.credentialengineregistry.org/resources/ce-59edbc9a-ee6c-4358-ad43-2325ee6c569c
![image](https://user-images.githubusercontent.com/21346519/135523397-ba2d87a6-28e0-4c6e-a232-29ec4f73d86e.png)

It's possible that other data could be affected as well.  Could this somehow be related to the SSL issue earlier?

**Comment by excelsior** [comment]
@siuc-nate The whole envelope containing the competency framework fails to get indexed for some reason, hence its description sets can't be generated. It doesn't appear to be related to context unavailability. I'm continuing the investigation…

**Comment by excelsior** [comment]
I found the issue finally, it's this property: `"ceasn:dateModified":"2021-04-23"`. In the context, the property is defined as `{"@type":"xsd:dateTime"}`, but the actual value is not a datetime, it's a date.

Because of that, there is a bunch of errors occurring when building RDF data, but my understanding was that it only affected the statements themselves, not the whole graphs. Besides, it only happens on sandbox, so I didn't pay much attention to that. I removed the problematic statement and indexed this envelope manually. I'll revisit the data in search of more errors like this. In the meantime, could you please fix the contexts on your side?

**Comment by siuc-nate** [comment]
I think the intent for those properties is to be a dateTime, but it seems we're only publishing the date part of it. @mparsons-ce Can you confirm?

**Comment by mparsons-ce** [comment]
@excelsior 
I have republished all of the credentials from the referenced spreadsheet. 
All of the dateEffective have been updated to use a full date.

**Comment by excelsior** [comment]
@mparsons-ce Thank you, will rebuild the index just in case.

**Comment by siuc-nate** [comment]
Thanks, closing this
