### ISSUE TITLE
Sporadic issues being unable to access a sandbox resource

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#492]
@excelsior 
I have been sporadically getting emails like the following when someone is trying to publish data. 
This one was while trying to publish a learning opportunity. 

```
RegistryServices.GetResourceByUrl: https://sandbox.credentialengineregistry.org/resources/ce-0bcba951-4801-4a88-ba4c-8754f3bd5b62

Type: System.AggregateException;
Session Id - unknown____IP - 52.158.209.227
Referrer: ;

Exception: One or more errors occurred.;
InnerException: An error occurred while sending the request.;
InnerException2: Unable to connect to the remote server;
InnerException3: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond **18.218.70.64:443**;
```
The IP address is usually the same (so the same publisher).

**Comment by excelsior** [comment]
@mparsons-ce I couldn't find anything relevant in our logs yet. When exactly did those failures happen? According to the monitoring tool we use, sandbox was down only thrice during the last week (each time for less than a minute).

**Comment by mparsons-ce** [comment]
@excelsior 
The issue occurs quite regularly. The messages all reference the IP address for the sandbox.  

`A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 18.218.70.64:443;`


11/30/2021 8:37:02 AM
RegistryServices.GetResourceByUrl: https://sandbox.credentialengineregistry.org/resources/ce-2d9f047a-2bd5-4131-a23b-3c77db4a8e95

11/30/2021 2:39:24 PM
RegistryServices.GetResourceByUrl: https://sandbox.credentialengineregistry.org/resources/ce-5328ef23-815b-4c37-90bc-c64acbd2291b

11/30/2021 2:23:23 PM
RegistryServices.GetResourceByUrl: https://sandbox.credentialengineregistry.org/resources/ce-c61da0e5-4ed9-4474-a98b-978ab37980ca

**Comment by neaf** [comment]
@mparsons-ce 

Hello,

Judging from the fact that that the failing request is actually getting a resource from the registry I assume that:

1. You first publish the resource
2. Then try to fetch it - **which fails** in publish flow but now the URLs return proper payloads (as I click on them)
3. 
Is that correct?

Also you pasted the following:
```
InnerException: An error occurred while sending the request.;
InnerException2: Unable to connect to the remote server;
InnerException3: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond **18.218.70.64:443**;
```

Based on that, can you reliably say whether it was actually a failed connection instead of a timeout on your side? Depending on that we'll know where to implement more visibility.

**Comment by mparsons-ce** [comment]
I have not seen any errors in the last month. 
I am closing this issue for now.

**Comment by mparsons-ce** [comment]
@neaf @edgarf 
I am having this consistently for the last 15 minutes. Retried many times. 
`The underlying connection was closed: An unexpected error occurred on a send.`

**Comment by excelsior** [comment]
@mparsons-ce Couldn't find anything suspicious at first glance. Could you please provide the exact resource ID which failed to load and the exact timestamps of when it happened. 

And just to double-check: The IP of the machine there are troubles of connecting to is 13.58.165.55, right?

**Comment by mparsons-ce** [comment]
@excelsior Yes, the IP is 13.58.165.55, 
CDT from 4/4/2022 3:44:05 PM to 4/4/2022 4:05:06 PM:

**4/4/2022 3:47:54 PM**: RegistryServices.GetEnvelope: https://sandbox.credentialengineregistry.org/ce-registry/envelopes/ce-cb986009-2818-402e-bd79-f1986ad3806a
Type: System.Net.WebException;

**Comment by neaf** [comment]
@mparsons-ce We're still moving forward by elimination but:

- Neptune was simply running out of memory. We were using deprecated 4GB machine while currently they offer minimum 16GB. I guess AWS realized it's simply not feasible to run it with lower amount.
- When Neptune run out of memory it simply stopped responding making our application server processes wait endlessly (with recently added 1 minute timeout)
- Even with the timeout it was possible to temporarily block all of the server processes. I didn't want to start with lower timeout value because I don't know what is the maximum "normal" time
- I'll continue monitoring the memory usage

**Comment by stuartasutton** [comment]
Why not stop "using a deprecated 4GB machine"?

**Comment by neaf** [comment]
We did today :)
