### ISSUE TITLE
Revisit community name presence in Authorization header

### ISSUE THREAD

**Issue by neaf** [CredentialEngine/CredentialRegistry#498]
We will also need to pass the organization CTID (to check for community access) in a parameter other than `Authorization Token`/`Authorization ApiToken` since that header is currently used for the CE admin key for endpoints like `description_sets`.  Or, if the CE admin key is detected, the community access check needs to be skipped. 

Suggestions? @mparsons-ce @excelsior @edgarf

_Originally posted by @siuc-nate in https://github.com/CredentialEngine/CredentialRegistry/issues/497#issuecomment-990361786_

**Comment by neaf** [comment]
Could someone shed a bit more light on the reason why we do this?

I see that we call an external service to verify whether given api key has access to specified repository. However, afterwards we don't seem to enforce it in any way. We still allow to select any community by url parameters.

Am I missing something?

@siuc-nate @mparsons-ce @excelsior @edgarf

**Comment by jeannekitchens** [comment]
@neaf I'd need to know more about the lack of enforcement.  I've touched on this with the related Registry Community issues but the requirements for a community are supposed to require a match to an authorized organization which orginates from the Credential Engine account system.  The account system identifies the organization, an internal account identifier, the organization's CTID and the API key.  

Authorized users with an approved organization that have an organizations CTID and an API key can use the publishing tools provided by Credential Engine.  In the case of SNHU, only their authorized users see the option to publish to the SNHU private community.  

The URIs to data in the Registry are meant to be open and anyone with a URI can access the resource or the graph.  With a private community, we need the option to lock down (secured) a community where only users issued an API key to consume the data can access it.  For example, we setup a secured community for the Navy that is secured.  In the case of the SNHU private registry, at some point we may need to change it back to secured but it should be disabled until we know what's in that community registry and can access all of the data in it just as we would need to be able to do for the Credential Registry.

I wanted to give you this information since you noted your coming into this blind.  Not sure if this backstory helps or not but bottom line for the SNHU Registry is (1) leave the secured disabled (thank you for changing this, (2) preference is not to have to create new CTIDs for everything in there this just causes double the work with no benefits as the data in this registry is for experimentation and testing and in now way is meant to interact with the Credential Registry, (3) the search needs to be fully functional with the data indexed and all description sets used with the Credential Registry.  

Let me know if this helps and what else you need.  Thanks!

**Comment by neaf** [comment]
@jeannekitchens, Every explanations as to **why** things are or should be given way is super helpful. Thank you 🙇‍♂️.

I also stand corrected, I found the place where we check whether user tries to access/affect proper community.

We do however always ignore the community name part of the `Authorization` token and use the URL prefix or default instead for validation.

@siuc-nate That means you can simply skip the community name in all cases.
