### ISSUE TITLE
AdditionalProperties and required

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/CredentialRegistry#5]
per @leolara
Two less important implementation details.

I think we should add "additionalProperties": false, to all things "type": "object", that is entities and sub-entities. Otherwise, people will be able to "invent" their own fields, and they will pass the validation.

Also I think at the bare-minimum each entity should have "required": ["ceterms": "ctid"], and preferably also other fields that are considered mandatory. It seems strange from a developer point of view that there are no mandatory fields and you can just create an accreditation just with an id.

I think that is all I could think from now based on the last version. I think the improvement is tremendous and that with a few tweaks we are there.

Regards,
Leo

**Comment by siuc-nate** [comment]
I had considered setting additionalProperties to false; I left it out for now since it's something we need to discuss.  Since CTDL is meant to be extension-friendly, that would seem to imply to me that we would want to allow additional properties and classes to be added by others.  @stuartasutton can you shed some light on this?

Regarding required properties, I agree we should determine some, but as yet we do not have any.  This would probably be a good issue for the vocabularies repository.

**Comment by leolara** [comment]
@siuc-nate at a bare minimum ctid should be set to required, I think

Of course, setting additionalProperties to false is a design decision, with pros and cons.

**Comment by leolara** [comment]
https://github.com/CredentialEngine/vocabularies/issues/344

**Comment by stuartasutton** [comment]
Nate says:
>I had considered setting additionalProperties to false; I left it out for now since it's something we need to discuss. Since CTDL is meant to be extension-friendly, that would seem to imply to me that we would want to allow additional properties and classes to be added by others. @stuartasutton can you shed some light on this?

Whether you permit additional properties or not in validation is a question of whether you are validating some constrained **profile** of the CTDL (e.g., stuff destined for the CER?) or the language as a whole. A **profile** of the CTDL can certainly be quite strict and preclude any additional properties and classes. The CTDL as a whole should be unconstrained (i.e., extensible) since one of its intentions is to support any number of distinct profiles. 

So, which are you talking about? CTDL as a whole or constrained **profile**? If you are defining a **specific profile** (i.e., a record structure) for use in a specific application, than not permitting additional properties makes perfect sense.

**Comment by leolara** [comment]
@stuartasutton I am talking about the storing in CER, so I guess that is a constrained profile.

I guess all work we are doing on JSON Schema is a constrained profile of sort. Not knowing enough about RDF.

So I guess, the conclusion is that it is ok to forbid undeclared properities on our JSON Schema, as that is a constrained profile and that does not make CTDL less extensible

**Comment by leolara** [comment]
@siuc-nate so should we actvate additionalProperties to false?

**Comment by siuc-nate** [comment]
Whether or not we want to allow extended/additional properties to be stored in the registry isn't my call - @stuartasutton @jkitchensSIUC we need to come to a decision. I don't have strong feelings on it either way, as properties not understood by a consuming system will almost certainly just be ignored by that system.

**Comment by leolara** [comment]
@siuc-nate otherwise, we will have to find a way to forbid ```@graph``` as it would be consider an additional property and they could put whatever there

**Comment by siuc-nate** [comment]
If we disallow additional properties at the document root level, can we still enable them in the other definitions?

**Comment by leolara** [comment]
@siuc-nate yes, my understanding is that for each type:object, you have an additionalProperties

So it can change at each level, and this property is not inherited or cascaded or something like that.

In JSON schema there is no inheritance or cascading, all these properties are for each sub-schema, and we need to explicitly say it for each sub-schema

**Comment by siuc-nate** [comment]
Having talked with @jkitchensSIUC we will disallow additional properties in the registry for now - but we may allow them later, depending on feedback we get from our technical committee. This should also make it easier to ensure that the validation is working properly during testing.

**Comment by leolara** [comment]
Perfect, please let me know and close this this issue, when this is already set in the grouped JSON Schema

**Comment by siuc-nate** [comment]
This has been done.
