### ISSUE TITLE
Missing description set data

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#507]
On production, the description set for framework `ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b` is missing the competency data (and their framework(s)) for the competency alignments for many of the competencies.  Most of these seem to be related to framework `ce-ee8c01f1-05fe-4d09-99ff-7dd4ec12a571`.

The connection usually goes through the `ceasn:narrowAlignment` property.

**Comment by jeannekitchens** [comment]
@edgarf @neaf the issue with missing description set data causes problems with the Credential Finder.  For example, this competency framework ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b is missing alignment data.  https://credentialfinder.org/competencyframework/1009/Education_Design_Lab_21st_Century_Skills.

This is an issue @siuc-nate has identified several times now.    What is the root cause?

**Comment by edgarf** [comment]
@siuc-nate @jeannekitchens  (cc @neaf ) - We are ready to deploy the new Description set functionality on production. Therefore, there wouldn't be much sense in debugging old code as it has been rewritten by Tomasz already. If we don't yet have the green light to deploy the description sets on prod tomorrow, then Tomasz will separately run his new code against the resources above. We can discuss more during the call!

**Comment by neaf** [comment]
Unfortunately I didn't click on the Finder link @jeannekitchens provided before running the code to compare but it looks like all of the competencies have some alignments now.

Can you confirm that fixes this issue? (cc @siuc-nate )

If so, my best guess is the root cause is the previous code not handling updates. Once we deploy the new code and regenerate descriptions sets for existing envelopes we should fix all such out-of-sync data cases.

**Comment by excelsior** [comment]
@siuc-nate There are two paths using the `ceasn:narrowAlignment` property:

1. < ceasn:isPartOf < ceasn:Competency > ceasn:narrowAlignment > ceasn:Competency
2. < ceasn:isPartOf < ceasn:Competency > ceasn:narrowAlignment > ceasn:Competency > ceasn:isPartOf > ceasn:CompetencyFramework

I double-checked and the above mappings seem to be producing correct results (70 and 2 unique competencies, respectively).

Could you please point out which competencies are missing and from which description set?

**Comment by jeannekitchens** [comment]
@excelsior here's an example based on ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b

This frameworks' competencies have numerous alignments to competencies in another, or other, frameworks.  The type of alignment e.g., narrowAlignment, name of the framework where the competency aligned to is located, and the competency aligned should be consistently displayed.  You can see in the Finder, it's quite inconsistent.  https://credentialfinder.org/competencyframework/1009/Education_Design_Lab_21st_Century_Skills
<img width="749" alt="image" src="https://user-images.githubusercontent.com/20917206/154287007-65ffe669-4ca0-44ed-abfc-85cb174ea741.png">

**Comment by siuc-nate** [comment]
Some of the data was missing previously, but it looks like it's all there now, even though it's still not displaying properly.  I will dig through this on our side and see if I can figure out what's going on
