### ISSUE TITLE
Getting 401 unauthorized errors on the production full text search

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#531]
We have been getting 401 errors on the full text search:
https://credentialengineregistry.org/ce-registry/search

Checking back this appears to have started yesterday. There evidence that the FTS was used before 22-03-06, but the issue could have started earlier.
I was testing comparing the FTS endpoint and the graph search. Both are using the CE authorization key beginning: b8b3c8. Actually the FTS was using the organization APIkey. This apparently worked before and works in the sandbox. I tried changing to use the CE authorization key as the latter was used with the graph search.

The graph endpoint completes successfully and FTS fails with a 401 code.

The FTS works fine on the sandbox.

**Comment by neaf** [comment]
@mparsons-ce For both `search` and `graph` actions we do token verification with the `https://{apps|sandbox}.credentialengine.org/accountsAPI/Organization/ValidateApiKey` endpoint.

It seems like it stopped allowing the token you are using.

The reason **it works** for `graph` is because the community has `secured` flag set to `false`. In such case the repository is public and token validation is skipped.
The reason **it works** on `sandbox` is because the community has `secured_search` flag set to `false` on that environment. In such case the search is open for public and token validation is skipped.
The reason **it doesn't work** on `production` is because the community has `secured_search` flag set to `true` on that environment. In such case we need the token validation endpoint to accept provided token.

We didn't change anything on our side related to authentication since I joined the project and haven't deployed anything to production since March 3rd.

`https://apps.credentialengine.org/accountsAPI/Organization/ValidateApiKey?community=ce_registry&apikey=b8b3c8[…]` has to accept the token you're using and it doesn't seem to at this moment.

**Comment by mparsons-ce** [comment]
@neaf 
The community ce-registry is public, and should **not** have **secured_search** to true. 
For both the graph search and the full text search, I was using the default community

**Comment by neaf** [comment]
@mparsons-ce 

I set `secured_search` on `ce_registry` to `false`.

This should resolve your initial issue. Default community always resolves to `ce_registry`.


That doesn't matter now, since we have no secured communities we're not using the `ValidateApiKey` endpoint, however, please note that most likely something did recently change there on your end.

**Comment by mparsons-ce** [comment]
Thanks @neaf 
While there was an update to the accountsAPI (on Mar. 6th, little surprise), there was no change to the ValidateApiKey  endpoint. 
I added some tracing for future reference.
