### ISSUE TITLE
Upgrade Postgres to latest minor version

### ISSUE THREAD

**Issue by science** [CredentialEngine/CredentialRegistry#540]
Upgrade and regression test to latest Postgres minor version.

Postgres has auto-update turned off, and I think we should also consider turning it back on - I think the way we use Postgres, we should not see minor version breaking changes (and I'd be surprised if major version upgrades break our usage patterns).

**Comment by excelsior** [comment]
The non-production DB has been upgraded to latest minor version (13.6, was 13.2). Will do the same to the production instance over the weekend.

I also tested the app locally against the latest major Postgres version available on AWS (14.2), and it turned out working just fine.

There's one problem, though: for some reason, the app doesn't re-establish the DB connection automatically when it loses it. So we can't enable auto minor version upgrade feature until we fix that issue.

**Comment by excelsior** [comment]
The production DB has been upgraded to 13.6 as well.

I implemented auto-reconnect in case of a DB downtime, that allowed us to enable the auto minor version upgrade flag for the non-production server.
