### ISSUE TITLE
Description Sets for Competencies

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/CredentialRegistry#545]
Need a consistent and timely way to address the needs for description sets.  Currently, Competency does not have a description set.  Need the Competency description set to implement a Competency detail web page. 

Nate's description set tool https://credreg.net/page/descriptionsetprofiles
description set mapping [spreadsheet](https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0)

**Comment by siuc-nate** [comment]
I have updated the spreadsheet to include rows (560 - 635) for Competencies, based on what we already had for Competency Frameworks.  I also included rows for the newer "substantiating" properties. I added similar rows for those (335 - 341) for Competency Frameworks as well.

This should give us enough of a starting point to work with until we can automate these.

**Comment by neaf** [comment]
@siuc-nate 

New mappings are on production and they seem to work. They will be generated on added/updated resources.

The problem is... In order to have the description sets for all current resources in our DB we'd have to re-run the generation for all envelopes. As of now it is a long and somewhat error-prone process (if Neptune fails) and we have no flow implemented to handle that.

I've communicated with Alex in order to:
1. Move the Postgres based generation forward by looking at the mappings generation logic provided by @siuc-nate and possibly porting it to Ruby
2. Create a process for more hands-off description sets re-generation for large amount of resources

Cheers
