### ISSUE TITLE
Disaster recovery test

### ISSUE THREAD

**Issue by mnguyenCred** [CredentialEngine/CredentialRegistry#627]
I am testing the disaster recovery environment for Credential Engine.  When I spin up the DR site in amazon aws, i get this error.

![image](https://user-images.githubusercontent.com/124899432/225737886-69330907-3dc8-4745-9f23-dfc81a7d9987.png)

The site mentions to run 'bundle install' to resolve the issue but when i try to log into the instance, i get this error

![image](https://user-images.githubusercontent.com/124899432/225738044-3175856e-d48e-4e22-9565-9e86ea39cb41.png)

**Comment by arielr-lt** [comment]
I'm looking through this issue...

**Comment by arielr-lt** [comment]
Hi Michael, I've just noticed that the issue is related to a hard-coded ruby version I set up (v3.1.2) when the app is deployed whereas one month ago the application's ruby version was changed to `v.3.2.0` , I've updated the DR deployment code to pick the ruby version from the application's `.ruby-version` file so that we no longer face this issue.  Please feel free to give it a try again @mnguyenCred .  I'll stay tuned for your feedback, cheers

**Comment by jeannekitchens** [comment]
@mnguyenCred what is the status of completing the testing of a new instance and disaster recovery?

**Comment by mnguyenCred** [comment]
Ariel and I are still working on getting the DR instance to run on my
machine.  Ariel is using a mac and I am on windows and we will need it to
work on windows because the navy is also using windows.  I have been
updating the trello ticket with statuses on what we are trying.

Man
