### ISSUE TITLE
Unable to publish to the registry

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#67]
We are not able to publish to the registry. The following message is always returned:
Unable to read data from the transport connection: The connection was closed

This started to occur on Friday, Apr. 14, 2017.

**Comment by coffeejunk** [comment]
I can publish without any issue from my end. How are you making the requests?

**Comment by cwd-mparsons** [comment]
@coffeejunk 
I tried the following search:
http://lr-staging.learningtapestry.com/api/ce-registry/search?resource_type=credential
and get:

> {
"errors": [
  "undefined method `config' for nil:NilClass"
],
}

Organization was published successfully on Apr. 10, but now I get a not found:
http://lr-staging.learningtapestry.com/api/ce-registry/envelopes/a7ad3bfd-177f-4566-b13f-a0a7a847df08

We use the following for publishing (which seems to now result in a 404):
http://lr-staging.learningtapestry.com/api/ce-registry/envelopes?update_if_exists=true

**Comment by coffeejunk** [comment]
@cwd-mparsons you need to remove the `/api` part from the URL (the `/api` has been removed in #62)

**Comment by coffeejunk** [comment]
Without the `/api` prefix the [search](http://lr-staging.learningtapestry.com/ce-registry/search?resource_type=credential) is still returning nothing because the `ce-registry` community is currently empty. 

We last cleared the database on the 12th of April which would explain why the above mentioned credential isn't accessible anymore (given that it was published on the 10th).

**Comment by cwd-mparsons** [comment]
thanks works properly now
