### ISSUE TITLE
Is necessary that fixtures/schemas/envelope.json.erb to be dynamic generated?

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#74]
It only has a dynamic thing here: https://github.com/CredentialEngine/CredentialRegistry/blob/b0c1e49f08b6aae825f34b16c72c11457928d5bb/fixtures/schemas/envelope.json.erb#L62

will it yield different values?

**Comment by andersoncardoso** [comment]
Before they were static, but at some point in time we started having common definitions appearing on several different schemas. 
To DRY we built this template schema rendering engine to reuse common definitions like `json-ld`, some `schema.org` classes, or common classes within a community. 

Unless this changed recently, the template rendering happens only once, on fixture load time, then it's stored on the db.

**Comment by leolara** [comment]
@andersoncardoso 

what does <%= ref :json_ld %> yield? Is not a url, like aways the same url?

I am not advocating to remove the schema render engine, I am not sure if it is needed for this file.

**Comment by andersoncardoso** [comment]
Currently, I think that after that refactor to fetch schemas from the db, this is only a helper for setting the proper filesystem path to the `json_ld` file. 

I.e: `<%= ref :json_ld %>` => `{"$ref": "/path/to/fixtures/schemas/json_ld.erb.json"}`

If I remember correctly, before this would set dynamically `$ref` to either be an URL for public schemas (i.e.: the ones served publicly on `/api/schemas/*` , or a path to the filesystems for internal schemas, used for the validation.

**Comment by leolara** [comment]
@andersoncardoso but then it will read the json-ld schema from fixtures always, it will not read it from the DB?

In that case it seems more interesting to have $ref pointing to an url.

**Comment by andersoncardoso** [comment]
For using the validation lib we need $ref to be a FS path, otherwise we would need a server running anytime we want to validate and save anything (including tasks, tests, console session, etc). 
When using for validation it uses the FS path, when we call `public_schema`[0] it parses `$ref` properly to an url.
If you don't want to point to a FS path, then we would have to embed the definitions into a single bundled schema (which is pretty ok actually).

[0] https://github.com/CredentialEngine/CredentialRegistry/blob/master/app/models/json_schema.rb#L17-L24

**Comment by leolara** [comment]
Closing this, seems to do not be an issue
